- .travis.yml
/cc @millerpuckette 
when i submitted the original `.travis.yml` file for inclusion, i did some extra step to document all the parts.
unfortunately, when doing so I introduced a `tab` (instead of `spaces`) which is a syntax error, and therefore the file is of no use.
this patch fixes this (as can be validated by the [travis-ci build](https://travis-ci.org/pure-data/pure-data/builds/121127918) triggered by this Pull Request)
> .travis.yml needs spaces instead of tabs

- src/s_audio_jack.c
- src/s_main.c
- src/s_stuff.h
I added a command-line argument and the appropriate additional code to set a desired name for the jack client that pd creates when enabled with `-jack -jackname thename`
This is especially useful if you'd like to run pd with multiple instances and be able to differentiate between them in your jack graph.
> jack client name

- src/s_audio_jack.c
- src/s_main.c
- src/s_stuff.h
Sometimes I don't want pd to automatically connect to any jack clients, this enables that. 
```
-nojackconnect
```
> added commandline option to disable jack automatic connections

- src/.dir-locals.el
the .dir-locals.el makes emacs apply Pd's indentation style to all C-files in this folder.
this makes it easier for people using emacs to submit files properly indented.
other editors are not affected...
> emacs configuration file for proper indentation

- doc/5.reference/message-help.pd
- src/x_time.c
- src/x_vexp.c
this fixes two memleaks (the expr-one recently discovered by @claudeha )
it also includes a minor help-patch fix, to get rid of a `$1 out of range` error when opening `5.reference/message-help.pd`
> Fix memleaks

- tcl/pdwindow.tcl
on X11, this ensures that windows are always opened at the same position.
so we can do `[vis 0, vis 1(` repeatedly without moving the window around...
the fix uses the pdwindow (once it is visible) to calculate the difference between the decorated window `wm geometry` and the `winfo xroot` ...
> calculate window position offsets (rather than hardcoding them)

- src/g_canvas.h
- src/s_stuff.h
This fixes redundant declaration, multiple definitions and avoid including `s_stuff.h` several times
> Fix redundant declaration

- src/g_numbox.c
the iemgui numberbox object unconditionally checks the type of the first argument, even if there the list is empty...
> fixed crash when receiving empty lists

- .appveyor.yml
- configure.ac
- src/s_main.c
- src/x_midi.c
this PR adds support for the [appveyor](https://appveyor.com) Continuous Integration service.
this is run a new test-build using Microsoft Visual Studio whenever something is pushed to the github repository (or whenever a pull request is made), allowing to find build failures early (given that nobody builds with MSVC regularily these days...).
The build is executed both in a 32bit and a 64bit environment.
The build logs can be found on the [appveyor project page](https://ci.appveyor.com/project/umlaeute/pure-data).
There are also artifacts attached to each (successful) build, which contain the produced binaries (the `bin/` folder), which can be downloaded for easy testing.
> appveyor support

- mac/README.txt
- mac/tcltk-wish.sh
- po/template.pot
* updated mac/README.txt based on feedback
* template.pot version was bumped, this gets picked up when using the auto tools build after the version string is changed in configure.ac
> mac app bundle README git usage clarification + template.pot version bump

- .gitattributes
- tcl/pd-gui.tcl
- tcl/pd_menus.tcl
- tcl/pdtk_canvas.tcl
- tcl/pdwindow.tcl
this is a follow-up fix for the window position problem as resolved in #44 (but which was effectively undone by merging in the `osx-retina-support` branch).
the PR also includes a `.gitattributes` file to exclude all the various dotfiles from the *source package* (as created via `git archive`)
> bugfix for windowpositions

- po/af.po
- po/az.po
- po/be.po
- po/bg.po
- po/de.po
- po/el.po
- po/en_ca.po
- po/eu.po
- po/fr.po
- po/gu.po
- po/he.po
- po/hi.po
- po/hu.po
- po/it.po
- po/pa.po
- po/pt_br.po
- po/pt_pt.po
- po/sq.po
- po/sv.po
- po/template.pot
- po/vi.po
- tcl/pd_menus.tcl
This PR removes the menu list string from the translations as it leads to a crash on startup when anything is actually changed. The individual entries are available for translation already.
> removed menulist strings from translations

- doc/5.reference/abs~-help.pd
- doc/5.reference/acoustics~-help.pd
- doc/5.reference/operators-help.pd
- doc/5.reference/until-help.pd
Fix the typo (and change the font size) of some help files, the name of the commits are explicits so you can do it manually if you prefer.
> Fix typo - help files

- po/af.po
- po/az.po
- po/be.po
- po/bg.po
- po/de.po
- po/el.po
- po/en_ca.po
- po/eu.po
- po/fr.po
- po/gu.po
- po/he.po
- po/hi.po
- po/hu.po
- po/it.po
- po/pa.po
- po/pt_br.po
- po/pt_pt.po
- po/sq.po
- po/sv.po
- po/template.pot
- po/vi.po
- tcl/pd_menus.tcl
This fixes an error with the menu binds which were calling menu_undo and menu_redo with the focused window argument. The problem is that neither of these procs requires an argument.
> fixed tcl error when using Undo and Redo menu entries

- po/Makefile.am
- po/af.po
- po/az.po
- po/be.po
- po/bg.po
- po/de.po
- po/el.po
- po/en_ca.po
- po/es.po
- po/eu.po
- po/fr.po
- po/gu.po
- po/he.po
- po/hi.po
- po/hu.po
- po/it.po
- po/pa.po
- po/pt_br.po
- po/pt_pt.po
- po/sq.po
- po/sv.po
- po/template.pot
- po/vi.po
- tcl/dialog_find.tcl
- tcl/pd_deken.tcl
- tcl/pd_guiprefs.tcl
- tcl/pd_menus.tcl
- tcl/pdwindow.tcl
> updates from test3 feedback

- src/m_class.c
The issue is explained here #129 and to avoid the crash we just need to avoid to free the symbols that are not allocated dynamically
> Fix pdinstance_free

- doc/5.reference/soundfiler-help.pd
- src/d_soundfile.c
Scratched an itch...
This PR adds a right outlet to [soundfiler] that sends out an info list on a read or write:
* samplerate
* headersize 
* number of channels
* bytes per sample
* big or little endian ("b" or "l")
The order is meant to match the argument order to the write -raw flag. The help patch was also updated.
I've tested with both the [soundfiler] & [readsf~] help patches as well as with files of varying types and sample rates. This should be safe as it's mainly only accessing values which were already parsed when reading the files. The only part I needed to add was parsing the AIFF 80 bit samplerate to an int but that was found online easily.
The last commit is only refactoring to use the new t_soundfile_info struct to cleanup some of the overly long function argument lists. If …
> [soundfiler] info right outlet

- po/af.po
- po/az.po
- po/be.po
- po/bg.po
- po/de.po
- po/el.po
- po/en_ca.po
- po/es.po
- po/eu.po
- po/fr.po
- po/gu.po
- po/he.po
- po/hi.po
- po/hu.po
- po/it.po
- po/pa.po
- po/pt_br.po
- po/pt_pt.po
- po/sq.po
- po/sv.po
- po/template.pot
- po/vi.po
- tcl/pd_guiprefs.tcl
- tcl/wheredoesthisgo.tcl
This small PR adds code to remove any non-existent files for the recent files menu if they fail to open when clicked on. It also adds a better error message.
> remove non-existent files from recent files menu

- configure.ac
A small bugfix for the --with-wish configure option override not being printed in the configure confirmation print. Also small fix for missing quotes on Windows.
> bug fix for --with-wish setting not being printed on not-macOS

- po/af.po
- po/az.po
- po/be.po
- po/bg.po
- po/de.po
- po/el.po
- po/en_ca.po
- po/es.po
- po/eu.po
- po/fr.po
- po/gu.po
- po/he.po
- po/hi.po
- po/hu.po
- po/it.po
- po/pa.po
- po/pt_br.po
- po/pt_pt.po
- po/sq.po
- po/sv.po
- po/template.pot
- po/vi.po
- tcl/dialog_path.tcl
- tcl/pd_deken.tcl
This PR adds an entry box to the Path dialog for the deken install path. A browse button lets you choose a new directory. This functionality is only added if the `::deken` namespace is is loaded.
This should eliminate the ambiguity as to where people might want to install things & puts this option into the "standard place" with the other paths.
~~Currently, the deken path is empty in a new install so this path shows nothing. That is normal behavior as deken, by default, installs to the ../extra dir for the first time and gives the user a prompt.~~
EDIT: We now show the default path if nothing is set, see updated screenshot
> Set deken install path in the Path dialog

- tcl/helpbrowser.tcl
This is a PR based on feedback from the 0.48 test releases. It mainly adds "live" interaction by refreshing the columns when navigating with the keyboard. This behavior is modeled on the macOS 
Finder column view (inherited from NextStep).
This builds on browser key bindings by Sebastian Shader: https://sourceforge.net/p/pure-data/patches/579/
Also, libdir display based on the current user search paths was brought back and exact path duplicates are now filtered. The core object help files no longer show in the root column as they can be found in Pure Data -> 5.reference.
Current TODOs:
Demo Video: <https://www.youtube.com/embed/2hL1brds1XA>
> helpbrowser: col output now updates based on key navigation

- tcl/pd_guiprefs.tcl
This PR fixes the currently buggy pd_guiprefs string quoting when calling exec with the macOS defaults command.
From my testing, I found that strings with special Tcl characters (parens, braces, curly braces) needed to be enclosed in single quotes while other strings without did not, merely having single quotes or spaces escaped with forward slashes. This also negates the need for shell expansion via calling `/bin/sh -rc`.
This approach is not foolproof though. Strings with both special Tcl chars and double/single quotes will cause problems but, hopefully that is an edge case. I added a catch around the write calls so these strings do not halt the GUI at least.
Also done: small cleanups regarding pref value init and moved pd_guiprefs variables out of the global namespace.
> pd_guiprefs string quote fix on macOS

- tcl/apple_events.tcl
- tcl/dialog_data.tcl
- tcl/dialog_find.tcl
- tcl/dialog_path.tcl
- tcl/pd-gui.tcl
- tcl/pd_bindings.tcl
- tcl/pd_menucommands.tcl
- tcl/pd_menus.tcl
- tcl/pdwindow.tcl
This PR addresses some keybinding issues & feedback from 0.48.0test5 (as well as other stuff I found):
* changed hsl bindings back to MOD-Shift-J, this fixes the MOD-Shift-H binding triggering the default "hide Pd" behavior on macOS
* cleaned up extraneous bindings (non-shift bindings don't need a double bind with uppercase, checking for TK 8.5 not really needed for most things), this was a vestige of my previous work updating things for TK 8.5+ on macOS & the upper case shift key bindings from IOhannes
* menu_print now uses the canvas window name + .ps extension for the default filename
* make sure find_dialog is raised on creation, this fixes Find sometimes opening behind a canvas window
* fixed find_dialog print, save, & saveas key binding pass through & update the menus to reflect …
> keybinding bugfixes & cleanups

- tcl/pd_deken.tcl
This small PR adds a verbose log print for the detected deken platform. This should be help when debugging issues with deken included in Pd.
This is also in a PR to the deken repo: https://github.com/pure-data/deken/pull/158
> verbose log print for deken platform

- po/es.po
I kept the directory name 'externals' untranslated, which I guess was made like this because of design and portability of this new feature. I will keep an eye if this changes.
> updated spanish translations

- tcl/dialog_path.tcl
- tcl/helpbrowser.tcl
- tcl/pd_menus.tcl
Yet more help browser updates, partially from test release feedback:
> Further helpbrowser updates

- doc/1.manual/x3.htm
I'm updating this manual entry.
It was originally saying Pd **does not** use the "Path" mechanism to search for files and externals, if you use a slash declaration: "/" - such as "../sounds/sample1.wav" or "../cyclone/cycle~"
But it actually does use the Path, so I changed it.
> Update x3.htm (entry about path mechanism was wrong)

- doc/1.manual/x5.htm
hi, I removed this mentioning of the "value" object, because that had in fact already been mentioned before, see notes for 0.47-0 release.
"Shahrokh Yadegari has updated the
source and made manifold improvements in the objects.  Notably, they now allow
access to variables in Pd defined via the "value" object."
The problem is that it wasn't then that it was able to access variables defined via "value" objects. In 0.47-0, expr version was upgraded to version 0.5, and this feature was added in expr version 0.4, which seems to pretty old, but older than that.
Anyway, maybe not a big deal and just leave as it is, but I thought it was pretty weird to mention this feature twice, in close versions in the release notes, saying it hadn't been mentioned before, when it actually had.
cheers
> expr mention in the release notes not accurate

- tcl/helpbrowser.tcl
- tcl/pd_deken.tcl
- tcl/wheredoesthisgo.tcl
This PR contains updates & fixes from the 0.48.0 test7 feedback
So far:
> Test7 updates & fixes

- src/g_canvas.c
- tcl/pd-gui.tcl
- tcl/pdtk_canvas.tcl
this is a re-implementation of PR #224, which:
- keeps the window-positions on X11
- is more optimized (check for hacks is only done on boot time (and therefore drops the `TCL_PATCHLEVEL` variable)
i've tested this on Debian but only with a standard dual-screen setup (main monitor to the left of right-monitor)
As reported on the pd-list, negative canvas window positions are clipped to 0 and/or reflected on the opposite screen border.
This PR fixes that by allowing negative positions to be sent to the window manager in Tk 8.5+ and keeps the clipping for Tk 8.4 as a fallback. Also, versions of Tk < 8.5.13 on macOS keep the clipping due to the buggy nature of the TK Cocoa backend up until that version.
This will need to be tested on all platforms but, from my research, it should be fine as …
> reimplemented "allow negative canvas positions in Tk 8.5+ for multi monitor support"

- src/s_inter.c
- tcl/pd_deken.tcl
this adds a small callback function to `deken`, so the Pd-core can send the proper architecture to the deken (since Pd-GUI can run on a different architecture than Pd-Core).
In Pd-core there is a corresponding function that sends the current architecture up (including OS, CPU, pointer-size and float-size)
the patch still ignores the `bits` field (i think the arch-string requires more discussion anyhow, see  pure-data/deken/issues/161)
> set deken arch from pd-core

- tcl/apple_events.tcl
- tcl/pd_menucommands.tcl
- tcl/pd_menus.tcl
This PR changes the Help menu on macOS when TK > 8.5:
* Pd Help menu now opens manual
* HTML Manual... entry removed
The Pd Help entry is created automatically by Tk Cocoa and cannot be changed or removed. This solution simple uses it in lieu of the HTML Manual... entry to avoid duplicate menu entries at the slight cost of a different menu entry name on 1 platform.
This fixes #172.
> Pd Help menu now opens manual

- src/d_soundfile.c
As reported by [Philipp Schmalfuß on the pd-list](https://lists.puredata.info/pipermail/pd-list/2017-10/120846.html):
>i ran into some trouble with the new features of [soundfiler]  
recently. It does not output the samplerate of .wave files correctly  
(haven't tried .aiff yet). With 96kHz files i got 30464, with 192kHz  
files 60928. Iemlib/soundfile_info did gave me the correct samplerate  
of the same soundfiles. So, is this a bug?
It seams using swap2() to convert the wave header sample rate byte values inadvertently drops some MSBs leading incorrect values for larger sample rate values. I've changed to using swap(4) which seems to work in my testing, but perhaps someone can double check the sample rate byte size in the WAVE format spec as I don't have time today.
EDIT: I just …
> fix for soundfiler truncating higher wave file samplerate values

- src/x_connective.c
This PR adds a right inlet to the [value] object as [suggested on the pd-list](https://lists.puredata.info/pipermail/pd-list/2017-10/120875.html).
Here's a test patch:
~~~
#N canvas 169 142 450 300 10;
#X obj 306 159 value b;
#X obj 86 132 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144 -1
-1;
#X obj 86 132 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144 -1
-1;
#X obj 306 130 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X obj 306 130 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X floatatom 86 190 5 0 0 0 - - -, f 5;
#X floatatom 306 189 5 0 0 0 - - -, f 5;
#X floatatom 185 39 5 0 0 0 - - -, f 5;
#X floatatom 185 137 5 0 0 0 - - -, f 5;
#X obj 159 57 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144 -1
-1;
#X obj 159 57 bng 15 250 50 0 empty empty …
> value right inlet

- mac/osx-app.sh
- mac/stuff/Info.plist
This PR updates the template Info.plist used in the Pd macOS app bundle:
* added UTExportedTypes keys for associated file type
* set UTTypeConfirmsTo so patch preview shows document icon instead of text file contents
* added mimetype info
* osx-app.sh now adds localization entries if .msg files are built
* organize Info.plist template keys alphabetically (they are alphabetized by PlistBuddy anyway)
This brings the vanilla Info.plist up to par with that used in Pd-extended.
> macOS .app info update

- src/g_canvas.c
This fixes libpd/libpd#214: libpd crashing when patch contains [declare -stdpath]
> check sys_libdir exists before reading it

- src/x_net.c
[netreceive] in TCP mode would create an outlet whenever you send it a "listen" message. instead create the outlet once in the new method. 
fixes https://github.com/pure-data/pure-data/issues/388
here's a minimal test patch:
[netreceive-test.zip](https://github.com/pure-data/pure-data/files/2130652/netreceive-test.zip)
> [netreceive] bug fix: don't create outlets on "listen" message.

- tcl/dialog_audio.tcl
- tcl/dialog_canvas.tcl
- tcl/dialog_midi.tcl
- tcl/dialog_path.tcl
- tcl/dialog_startup.tcl
This is a quick fix to hide dialogs which resize on creation and raise after sizing to fit, affected dialogs are: audio, midi, path, startup.
Basically, on macOS I'm seeing the dialog window be created, then resized and moved which looks like a jarring visible "jump." it doesn't seem to happen with all versions of Tk, but does with the current Pd 0.48-1 release and my macOS 10.13 system.
The simple fix is to hide the window as after it's created then raise it after it's been sized and moved. There shouldn't be a noticeable change in behavior on other platforms.
Also included are a couple small dialog layout tweaks, including aligning the "Use callbacks" label with it's associated button.
> hide dialogs which resize on creation and raise after sizing to fit

- src/m_class.c
- src/m_pd.h
this implements a simple, API-compatible mechanism to prevent double-precision externals from being loaded into a single-precision Pd and vice versa, as [proposed on the mailnglist](https://lists.puredata.info/pipermail/pd-dev/2015-02/020073.html) and mentioned in #299 
- single-precision (`PD_FLOATTYPE==32`) externals use `class_new()` to register new classes
- double-precision (`PD_FLOATTYPE==64`) externals use `class_new64()` to register new classes
if an external uses the wrong variant of `class_new` (e.g. `class_new64()` on a single-precision Pd host) will yield an error message and the class will not be registered (with `class_new` returning `NULL`).
API compatibility is kept by using a pre-processor define, so externals keep using `class_new` in their code, but it gets magically …
> prevent double-precision externals from crashing a single-precision Pd (and vice versa)

- src/g_canvas.c
This fixes a display "bug" where signal patch cord corners can be seen at certain patch cord angles between objects. The fix basically introduces a y offset based on the inlet/outlet height and zoom setting.
The only downside I can see is that the current PR introduces some extra math when updating the canvas io. This could probably be avoided by precomputing the offset and storing it somewhere.
Quick examples at zoom 2. Notice the corner of the [osc~] outlet cord showing beyond the object border.
> offset patch cord y pos to center within io

- src/d_fft_fftw.c
Steps to reproduce:
1) Set PD_FLOATSIZE to 64
2) configure pd with --enable-fftw
The current master branch fails to build because of mismatch between declarations of mayer_*() in m_pd.h and d_fft_fftw.c. This fixes the build.
> FFTW integration: Fix build with PD_FLOATTYPE != float

- src/s_audio.c
- src/s_audio_pa.c
- src/s_main.c
* prevent Pd from hanging when you choose an audio device blocksize larger than 64 and accidentally set a delay which is shorter than your block size
* check for "-h" and "-help" early on, before opening audio devices because this might take some seconds when you have Jack on Windows (and the server isn't started). this can be a bit unnerving when you only want to see the help
* prevent Pd from hanging when a device gets disconnected. we set a timeout for polling/waiting after which Pd prints an error and tries to reopen the audio device. if that fails, Pd closes the device and the user can later reopen it from the menu. this works for FAKEBLOCKING with and without THREADSIGNAL. I also added the error handling to the blocking mode (which didn't really hang Pd)
> Fix audio issues related to portaudio

- src/s_audio_pa.c
replace the private PaUtil_ValidateStreamPointer with the public Pa_IsStreamActive. 
solves https://github.com/pure-data/pure-data/issues/450#issuecomment-420761829
lesson learned: stay away from private headers
> fix regression in portaudio

- doc/5.reference/declare-help.pd
I removed a comma that I don't thing belonged anywhere.
so whete it did read "you can put an object, "declare -path more" to make sure "
it now read "you can put an object "declare -path more" to make sure "
> minor fix in declare-help.pd

- doc/5.reference/drawtext-help.pd
- doc/5.reference/help-intro.pd
added references to [drawtext] and [drawsymbol] into help-intro.pd
added [drawtext] in drawtext-help.pd file as it wasn't mentioned anywhere in any help file... and seems like it could be into drawtext-help.pd if any :) - but I didn't add any information on what it does or what's different about, because I just have no idea!
> add missing  [drawtext] / [drawsymbol] objects to documentation

- src/s_inter.c
- src/s_path.c
- tcl/helpbrowser.tcl
- tcl/pd-gui.tcl
- tcl/pd_deken.tcl
This PR adds sending of the `st_temppath` core paths from the commandline `-path` option to GUI so it they be used for plugins, helpbrowser, and deken. This is accomplished by adding a new GUI variable ` $::sys_temppath`. This should fix the regression of `-path` not be used for loading GUI plugins.
This is a fix for #483 which was introduced when separating the `-path` temporary paths from the savable `st_searchpaths`.
> send st_temppath to GUI

- src/x_interface.c
also, only omit the "list" selector if the list starts with an A_FLOAT
(rather than *not* starting with an A_SYMBOL)
Closes: https://github.com/pure-data/pure-data/issues/540
> avoid colon (and leading whitespace) when printing lists with [print -n]

- src/s_inter.c
- src/x_net.c
* this makes sure that 10054 errors are really ignored on Windows so sending to a non-existing destination with [netsend -u] won't close the socket
* only set SO_BROADCAST on stream sockets to avoid bogus error messages "failed to set SO_BROADCAST" when creating a [netreceive] (TCP) object
> [netsend -u]: Windows related bugfixes

- doc/5.reference/pdcontrol-abs.pd
- doc/5.reference/pdcontrol-help.pd
- src/x_gui.c
here's a suggestion to get the patch's arguments as a list with a new 'args' method with the new [pdcontrol] object.
> pdcontrol args method

- src/s_midi_pm.c
currently, [midiin] and related objects stop responding if too many MIDI messages are sent in short time intervals and you have to reset the MIDI device in the MIDI dialog. I've tested this with a MIDI loopback and it already happens after sending 3 MIDI bytes every 1 ms.
there were two problems in the Pd code: 
* sys_poll_midi used an if clause instead of a while loop so the midi queue doesn't get flushed properly (and the `throttle` variable was useless)
* the call to Pa_Poll is redundant and also doesn't report overflow errors. this means that sys_poll_midi would stop reading midi messages once an overflow occured.
fixes https://github.com/pure-data/pure-data/issues/554
> fix MIDI overflow handling for portmidi

- src/d_math.c
This is a fix for an issue I encountered when using libpd in my own [Unity wrapper](https://github.com/LibPdIntegration/LibPdIntegration) for the library (you can read the original issue [here](https://github.com/LibPdIntegration/LibPdIntegration/issues/6)).
In d_math.c there are a number of objects which, in their perform function, define the block size as a t_int variable. This causes problems on 64-bit Windows binaries, because the block size is originally defined as an int (32-bits on Windows). Because t_int is defined as a long long (64-bits) this results in the perform function of these objects reading a junk value in the upper 32 bits of the t_int and attempting to process the wrong number of samples.
The affected objects are:
rsqrt~
sqrt~
wrap~
mtof~
ftom~
dbtorms~
rmstodb~ …
> Fix for issue with t_int on 64-bit Windows for d_math objects

- src/m_pd.h
The correct check for 64-bit Windows is `_WIN64`, not  `__x86_64__` which just happens to be defined by MinGW. 
Yesterday I've been scratching my head why my 64-bit MSVC build of a external would crash Pd (with a wiped out stack) while the MinGW build would not...
> fix PD_LONGINTTYPE for 64-bit windows

- doc/6.externs/dspobj~.c
- extra/bob~/bob~.c
- extra/bonk~/bonk~.c
- extra/fiddle~/fiddle~.c
- extra/loop~/loop~.c
- extra/lrshift~/lrshift~.c
- extra/pd~/pd~.c
- extra/sigmund~/sigmund~.c
- src/d_arithmetic.c
- src/d_array.c
- src/d_ctl.c
- src/d_dac.c
- src/d_delay.c
- src/d_fft.c
- src/d_filter.c
- src/d_global.c
- src/d_math.c
- src/d_misc.c
- src/d_osc.c
- src/d_resample.c
- src/d_ugen.c
- src/g_io.c
`dsp_add` is a variadic function which expects all arguments to be of type `t_int`; pushing arguments of a different size, e.g. `int` on a 64-bit platform, is undefined behavior. This has caused actual problems with 64-bit MSVC builds on Windows. For a more detailed explanation, see https://github.com/pure-data/pure-data/pull/673#issuecomment-508223766.
This PR makes sure to cast every integer to `t_int` before pushing it to `dsp_add.`
> avoid undefined behavior in 'dsp_add'

- src/Makefile.am
- src/makefile.mac
- src/s_file.c
This PR introduces direct plist preference reading and writing on macOS. This greatly increases performance as compared to the previous method of calling the `defaults` command through `system()`.
In (informal) testing, read and write times go from around 3-4 seconds to barely imperceptible.
This uses the CoreFoundation C framework and should build back to OS X 10.6 without issue. I did some reorganization by splitting out the various platform-specific implementations into separate sections.
> read and write to mac plist on directly

- doc/5.reference/drawpolygon-help.pd
- src/g_template.c
while "-xr" disables *all* mouse actions in run mode, "-xv" only disables changing vertices while still reporting mouse clicks to the struct.
example use case: build a GUI with data structures but prevent the user from accidentally change the shape of the widgets.
> add flag to [drawpolygon] to only disable changing vertices

- src/g_traversal.c
if the gpointer of the message points to the same thing (scalar or word) as the stored pointer,
output the pointer.
if they are not equal, send a bang through the last outlet.
EDIT: the result could also be sent as float (0 or 1) to the last outlet. I'm starting to like this better because it wouldn't interfere with the rest of the interface (the user can use [route bang float] on the last outlet)
alternative implementation: https://github.com/pure-data/pure-data/pull/435
> add message to [pointer] to test gpointers for equality

- src/g_all_guis.c
Restore `glist_isvisible()` protection for `send()`, `receive()`, `displace()` and `select()` methods.
Closes #477, that was happening again, when loadbang-setting a receive/send name of an iemgui located inside of a GOP, itself contained into a non-GOP patch.
> fix iem gop again

- src/d_ugen.c
- src/m_imp.h
- src/m_pd.h
This exports the `obj_findsignalscalar` function.
This function is currently used by some plugins in [cyclone](https://github.com/porres/pd-cyclone). See [here](https://github.com/porres/pd-cyclone/search?q=obj_findsignalscalar&unscoped_q=obj_findsignalscalar).
I was not sure where to put it in the header file. Please let me know if I should put it somewhere else.
> Export obj_findsignalscalar function

- doc/5.reference/openpanel-help.pd
- src/x_gui.c
- tcl/wheredoesthisgo.tcl
this PR adds an optional 'mode' argument to [openpanel]:
0: choose a single file (the default)
1: choose a directory
2: choose multiple files (output as Pd list)
this feature is fully backwards compatible
> [feature]: add 'mode' argument to [openpanel]

- doc/5.reference/value-help.pd
- src/x_connective.c
this method allows to directly send the stored value to a named object (e.g. [receive] or another [value]), analogous to the [send( method of [float], [int] and [pointer].
> [feature]: add [send( method to [value] object

- src/g_editor.c
- src/g_text.c
With pd 0.50, Canvas Properties dialog values are inconsistent whether you open it  with zooming = 1 or with zooming = 2 (the margins and offset are halfened with zoom = 2).
The proposed fix restores consistent displaying of the margins and offset values in canvas properties dialog box, when gop enabled, independently of zoom displaying factor.
This fix may also restore consistent behaviour of donecanvasdialog message between pd 0.49 and pd 0.50, with zoom = 2.
> fix GOP-Canvas Properties dialog issues when zoom = 2 (and fix another zoom bug)

- README.txt
- src/Makefile.am
- src/d_soundfile.c
- src/d_soundfile.h
- src/d_soundfile_aiff.c
- src/d_soundfile_caf.c
- src/d_soundfile_caff.c
- src/d_soundfile_next.c
- src/d_soundfile_wave.c
- src/makefile.gnu
- src/makefile.mac
- src/makefile.mingw
- src/makefile.msvc
This PR is built upon #855 and adds CAF File support (Core Audio Format File).
CAF was designed by Apple but the [specification is open](https://developer.apple.com/library/archive/documentation/MusicAudio/Reference/CAFSpec/CAF_intro/CAF_intro.html#//apple_ref/doc/uid/TP40001862-CH203-TPXREF101) and there is support for it in other software and systems beyond the Apple sphere. It supports 64 bit chunk sizes so audio data > 4 GB can be handled and samples can be either little or big endian. The layout is similar to AIFF, so it was not too difficult to implement.
I have tested both reading and writing 16 bit, 24 bit, and 32 bit float, mono and 4 channels and have compared the header info with that displayed by `soxi -V4`:
~~~
$ soxi -V4 test4.caf
soxi INFO formats: detected file format type …
> [WIP] CAF audio file support

- tcl/dialog_message.tcl
Fixes #923
The problem is caused because the .message window gets destroyed *before* [this binding](https://github.com/pure-data/pure-data/blob/e2ef8158e83900734d263a3fda343a47ed0c9e3a/tcl/pd_bindings.tcl#L118) is executed.
> Fix TCL error when closing the message dialog

- msw/pd.nsi
Two bug-fixes for the Windows installer:
- Allow double-click to open .pd files with "white space" in name. Closes #759
- Windows: calling installer multiple times _should not_ change target path. Closes #763
Both tested.
> Windows installer (2  bug-fixes)

- src/g_template.c
There has been a regression in Pd 0.50 (I think), where hovering over a vertex in a data structure array will show the same cursor as for changing the line width (double arrow) instead of a the "click me" cursor. This PR restores the original behavior.
Also adds some comments and fixes a possible segfault :-)
> fix data structure array cursor

- mac/Makefile.am
- mac/README.txt
- mac/osx-app.sh
- mac/stuff/pd.entitlements
This PR adds a code signing step when building the macOS .app bundle in order to set an entitlement to allow un-validated dynamic libraries to be loaded:
https://cutecoder.org/programming/shared-framework-hardened-runtime
This is required in order for Pd to load older externals (built with min macOS deployment version < 10.9) without a validation warning and manual steps to allow loading in the Security & Privacy preferences panel on macOS Catalina 10.15+.
The signing identity is "-" which performs an "ad-hoc code sign" aka the bundle is not actually signed with a developer certificate. This means the first run "unidentified developer" warning remains. We could add a developer identity later, if needed.
EDIT: From the original pd-list post by Kevin Haywood:
> I just discovered the huge …
> ad-hoc code sign to set library loading entitlements for macOS 10.15+

- src/m_pd.h
- src/s_file.c
This is a small bugfix PR which fixes some preference strings being read as NULL preference on macOS by using CFStringGetCString instead of CFStringGetCStringPtr.
The [Apple docs](https://developer.apple.com/documentation/corefoundation/1542133-cfstringgetcstringptr?language=objc) mention that CFStringGetCStringPtr may return NULL even if the string value is valid. It then mentions to use CFStringGetCString as a backup. In this case, we need to have our own copy so it makes sense to simply use CFStringGetCString anyway.
> fix reading NULL pref strings on some macOS versions

- mac/osx-app.sh
This is a *possible* fix for code signing issues when building the macOS .app bundle.
Following this [Stack Overflow post](https://stackoverflow.com/questions/7697508/how-do-you-codesign-framework-bundles-for-the-mac-app-store), apparently bundled frameworks must be explicitly signed as the --deep flag will not actually handle this on it's own. Go figure.
Please test.
> explicitly sign bundled frameworks when creating mac app

- mac/README.txt
- tcl/pd_guiprefs.tcl
This is a quick PR which disables "dark mode" for the Pd GUI on macOS 10.14+.
Setting the NSRequiresAquaSystemAppearance default to true instructs the system to use the default "light mode" when opening the Pd GUI. This was not a problem with earlier versions of Pd using TK 8.5, but the newer Tk 8.6 is dark mode aware and result in a mismatch of light text on light backgrounds etc as the GUI is using a light-oriented color scheme.
Until we get around to full supporting dark mode, this triage fix will keep Pd legible for now.
> disable dark mode for GUI on macOS 10.14+

- tcl/pdtk_canvas.tcl
This small PR sets the canvas background color too white. On most systems, this is automatically white anyway, but newer versions of macOS using Tk 8.6 will use the system default gray.
*Original idea from @umlaeute on the pd-list*
> set canvas background color for macOS and newer Tk versions

- src/m_binbuf.c
- src/m_class.c
- src/x_connective.c
- src/x_interface.c
* `[print]`: print a single gpointer as `(pointer)` for consistency with all other objects
* `[print]`: correctly print a list containing a single gpointer (the current code accidentally prints a symbol selector)
* `[route]`: correctly forward a single gpointer (the current code accidentally sends the gpointer as a symbol!)
* `[trigger]`: fix gpointer error message
* `pd_typedmess`: check for gpointer, so we can't type bogus messages like `[pointer foo(`, just like we can't type `[float foo(`. This also ensures that `gpointer -> [pointer $1(` stays a gpointer message.
* `binbuf_eval`: check for gpointer selector, so we can pass a gpointer to `[$1 ...(` (the current code just silently ignores the message).
> several gpointer bugfixes

- src/m_pd.h
In m_pd.h it checks for `_MSC_VER`, and if defined it inlines a tiny fake stdint.h instead of including stdint.h, noting "Visual Studio is not C99".
However, [since VS2015](https://docs.microsoft.com/en-us/previous-versions/hh409293(v=vs.140)#c-runtime-library) many C99 headers including stdint.h have shipped with MSVC.
So for `_MSC_VER` greater than or equal to 1900 ([Visual Studio 2015 / Visual Studio 14.0](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019)) it is safe to simply include stdint.
This would be a good change because it prevents conflicts when you include both m_pd and stdint.h in a file compiled with modern MSVC, which is something I experienced using libpd while testing #1096.
I have not exhaustively tested this patch with different versions …
> Augment _MSC_VER check on stdint include to check _MSC_VER number

- src/g_rtext.c
fixes a problem with updating GOP display just before closing the window containing the GOP.
Closes: https://github.com/pure-data/pure-data/issues/814
> only send rtext-data if there's an actual window to send it to

- msw/build-wxp-32.sh
- src/g_all_guis.c
- src/m_pd.h
- src/makefile.mac
- src/makefile.mingw
- src/s_audio.c
- src/s_audio_jack.c
- src/s_inter.c
- src/s_midi.c
- tcl/dialog_audio.tcl
- tcl/dialog_font.tcl
- tcl/pd_bindings.tcl
- tcl/pdwindow.tcl
this is meant as a successor of the update/0.51 and similar PRs (where it was always a bit awkward to have the Pd target-version embedded).
the idea is to have a permanent branch develop that only gets curated, small, no-brainer changes that can be easily merged into master at any time.
PS: if anybody can explain how to create PRs that are kept open after merging (or at least: can be opened again after merging), that would be fantastic. (it's a bit boring to re-open this PR after each release ;-))
PPS: supersedes #1105
---
Fixes included (this list should get updated whenever a new fix is included. keep in mind that updating the list might be forgotten though...)
- GUI-stuff
- #814 (tcl-error when updating a closed GOP)
- #1152 (some keyboard shortcuts don't work with <kbd>CapsLock</kbd> …
> stable development branch

- INSTALL.txt
- mac/README.txt
- mac/osx-app.sh
- mac/patches/tk8.6.10_keyfix.patch
- tcl/pd_bindings.tcl
This PR brings fixes for the following issues with TK 8.6.10:
1. ports the macOS key release handling patch from 8.5.9 to 8.6.10 which fixes key release and key repeat\*
2. adds event handling for the character composition events, ie. creating a ü by pressing opt+u then u
With composition, an interim character is usually shown, then replaced by the final character after the composition succeeds. For ü, ¨ is shown after the opt+u until the second u is pressed. Pressing escape during composition will leave the interim character. For the Pd GUI, the easiest solution might be to send a virtual/fake BackSpace to the Pd core to remove the interim character.
Tk 8.6 has added events for when composition starts, ends, or is cancelled which I found y looking in `library.entry.tcl` to see how the …
> [WIP] macOS Tk 8.6.10 key handling fixes

- src/g_text.c
This PR is a fix for #1101 by walking back to the previous unicode code point which could multiple-characters.
> fixed symbol atoms not handling multi-byte chars on backspace

- src/x_text.c
use thread-local storage to make `stupid_sortcompare` thread-safe, so we can use it in multi-instance libpd builds. also fixes https://github.com/pure-data/pure-data/issues/675
> text sort: apply MSVC hack to Emscripten and Android

- mac/stuff/Info.plist
- mac/stuff/pd.entitlements
It seems that if using Xcode SDK 10 and later, OSX won't prompt for user permission to use the camera and will just terminate the process unless there are certain lines that indicate those resources will be used in the bundle's Info.plist file. I also added a microphone entry. (Using the camera from the Pd bundle is necessary for ofelia, for example)
https://eclecticlight.co/2018/08/27/mojaves-privacy-protection-is-complex-and-will-crash-innocent-apps/
I wasn't sure what to put for the panel's message
> Add entries to Info.plist and pd.entitlements for Xcode SDK > 9

- tcl/dialog_find.tcl
- tcl/helpbrowser.tcl
- tcl/pd_deken.tcl
- tcl/pd_guiprefs.tcl
- tcl/pd_menus.tcl
- tcl/pdtk_canvas.tcl
Found via `codespell v2.0.dev`
> Fix typos in tcl/ directory

- doc/1.manual/x2.htm
- doc/1.manual/x3.htm
- doc/5.reference/hradio-help.pd
- doc/5.reference/hslider-help.pd
- doc/5.reference/int-help.pd
- doc/5.reference/line-help.pd
- doc/5.reference/line~-help.pd
- doc/5.reference/makefilename-help.pd
- doc/5.reference/my_canvas-help.pd
- doc/5.reference/netreceive-help.pd
- doc/5.reference/numbox2-help.pd
- doc/5.reference/slop~-help.pd
- doc/5.reference/threshold~-help.pd
- doc/5.reference/toggle-help.pd
- doc/5.reference/vdl-help.pd
- doc/5.reference/vline~-help.pd
- doc/5.reference/vradio-help.pd
- doc/5.reference/vslider-help.pd
- doc/5.reference/vu-help.pd
- doc/6.externs/0.README.txt
Found using `codespell v2.0.dev`
> Fix typos in doc/ directory

- doc/5.reference/savestate-help.pd
this adds a paragraph explaining the when using `[savestate]`, the user shouldn't assume that they can send data to objects outside of the abstraction.
Closes: https://github.com/pure-data/pure-data/issues/1201
> Note that [savestate] fires before connections are made

- font/README.txt
- mac/README.txt
- src/s_main.c
- tcl/pd-gui.tcl
This PR changes the default font for macOS to Menlo. This is a hack until the render issue (#988) with DejaVu Sans Mono can be fixed on macOS 10.15+.
This only sets a new default font family name. DejaVu Sans Mono is still included in the app bundle for now which should help with testing once we have a fix for the rendering issue. Documentation on this change is included in `font/README.txt` and system-specific `mac/README.txt`.
> macOS default font Menlo (for now)

- configure.ac
right now, the `--disable-portaudio` flag disables PortAudio support, but still compiles the embedded copy of the PortAudio library (it just skips the linking step).
this is suboptimal, as it
- requires more ressources to compile
- is error prone (cf #1072 )
this PR completely disables PortAudio if the user passes `--disable-portaudio`.
the same goes for PortMidi.
Closes: #1072 
this PR also replaces the few remaining uses of bash's `if/else` and `switch/case` constructs to the autotools' `AS_IF` resp. `AS_CASE` macros.
> Disable local-portaudio if portaudio is disabled in general

- src/d_soundfile.c
Make sure that Pd doesn't get stuck in an infinite loop if `open` or `write` fails in `writesf_child_main`. Also print error message.
The code basically follows the one in `[readsf~]`, with slight adaptions where necessary.
Fixes https://github.com/pure-data/pure-data/issues/1211
NOTE: this has been incorporated into #855
> writesf~: fix unfinite loop on I/O error

- mac/patches/README.txt
- mac/patches/tk8.6.10_helpmenu.patch
- tcl/pd_menus.tcl
This PR adds a patch for Tk 8.6.10 on macOS which fixes items in the Help menu being disabled after windows are cycled and not re-enabled. This is basically a fresh bugfix back port from upstream Tk development and is an alternate to #991.
Also, the `mac/patches/README.txt` has been updated with info on what each patch does.
> Fix disabled Help menu items on macOS

- src/d_soundfile.c
When Pd (or libpd) is compiled with `PDINSTANCE` and `PDTHREADS`, the child threads of [readsf~] and [writesf~] need to have `pd_this` correctly initialized to the pd_instance that owns the object, else Pd crashes.
This closes #1225
> set pd_this for readsf and writesf child threads

- src/s_net.c
The BSD libc currently has a bug where `getaddrinfo()` returns `EAI_BADFLAGS` for the `AI_ALL` and `AI_V4MAPPED` flags.
This essential means that we can't use dual stack sockets, so we simply fall back to IPv4.
NOTE: this apparantly also affects Android!
Fixes https://github.com/pure-data/pure-data/issues/1229
> addrinfo_get_list: hack for Android and BSDs

- tcl/pd_bindings.tcl
due to the different way tk handles timing (on osx at least) in the current 8.6 branch, the incorrect width and height might be the last values sent to pd (as of tk commit: https://core.tcl-lang.org/tk/info/491f5a56ddf503da). Therefore they should be set to the correct values after update idletasks
> change width and height to be correct after update idletasks in ::pd_bindings::patch_configure

- src/g_editor_extras.c
when selecting a line between two objects and then pressing ctrl + t, the new trigger box (or pd nop~) is created in the wrong place if the first object (source) height is bigger than default object height (due to its gop properties enabled).
image.
The proposed modification in g_editor_extras.c fixes this issue.
This pull request substitutes https://github.com/pure-data/pure-data/pull/1241
> fixed vertical offset issue in triggerize_line fn

- src/g_editor.c
with zoom = 2, the undo behaviour was inconsistent after moving an object with mouse / keyboard arrows
> bugfix when undoing object move while zooming x 2

- src/g_graph.c
- src/g_text.c
> make sure object is visible for drawing cords and gatom labels when displacing

- mac/README.txt
- mac/patches/README.txt
- mac/patches/tk8.6.10_scrollbars.patch
- mac/patches/tk8.6.10_zombiewindows.patch
- mac/stuff/Info.plist
- tcl/dialog_audio.tcl
- tcl/dialog_font.tcl
- tcl/dialog_message.tcl
- tcl/dialog_midi.tcl
- tcl/dialog_startup.tcl
- tcl/pd_menucommands.tcl
I'm lumping in a few other fixes to this PR in lieu of opening a new one (lazy).
This PR fixes #1237 by adding a Tk 8.6.10 patch which backports commit for scrollbars on macOS 10.14 (and probably newer versions as well).
Apparently, they were not being updated on some events, so the TK scrollbars are not (re)drawn resulting in this for a patch with 1 object with a far xy location:
The same type of patch looks like this with this PR applied:
> macOS fixes for 0.51-4

- src/m_pd.h
In order for Windows to successfully link applications with a
static build of libpd, the __declspec portion of EXTERN needs
to be left out, which can be done by defining EXTERN manually.
> Fix undefined references when linking a static build of libpd in Windows

- tcl/dialog_path.tcl
i'm removing "fonts" from the path's top description. This is misleading as it can make someone (like me) believe Pd handles fonts easily when this is only true for Gem and Gem's documentation makes it clear that you can have fonts in your path that it'll handle.
I just replaced for other file types that actually make sense for Pd (audio/text) and also made ir vague that you can have "other" files. But I didn't get into that... if I tried to tell people that externals may open different kinds of files, i'd take up too much space.
> Update dialog_path.tcl (remove "fonts", add "audio/text" in top description)

- m4/universal.m4
- src/s_inter.c
- tcl/pd_connect.tcl
- tcl/pdwindow.tcl
currently the GUI crashes when printing *large* amounts of data, as can happen when accidentally `[print]`ing a counter that 
(#345).
a very simple example of such a crashing patch is:
~~~pd
#N canvas 851 401 450 300 12;
#X msg 86 46 1e+07;
#X obj 86 71 until;
#X obj 86 121 print;
#X msg 86 96 1 2 3 4;
#X connect 0 0 1 0;
#X connect 1 0 3 0;
#X connect 3 0 2 0;
~~~
there were several underlying issues:
- the Pd-console keeps all messages ever printed (unless explicitely cleared). this obviously fills the memory over time.
- an integer-overflow when allocating more memory for gui messages
- untested and broken code leading to data loss (and thus un-executable tcl-code) in the core->gui communication was triggered whenever such an integer-overflow occured
- the GUI - hoping to recover from …
> allow large amounts of data to be sent to the GUI (and limit the Pd-console's length)

- src/s_audio_jack.c
This removes the arbitrary `100` byte limit on JACK client names in
favour of using the limit specified by JACK itself.
From the [JACK docs][1]:
> `jack_client_name_size()`
>
> the maximum number of characters in a JACK client name including the
> final NULL character. This value is a constant.
If I `printf` the value locally, the constant turns out to be `128`.
I ran into this issue as I happen to have a default client name on my
device (Dell XPS 9310) that is `108` bytes long heh! This meant that
when selecting "jack" in the "Media" menu, pd would instantly crash.
See NixOS/nixpkgs#118835 for how I debugged and solved this.
After applying this patch, I can now use pure data with JACK
successfully.
[1]: https://jackaudio.org/api/group__ClientFunctions.html
> Fix "buffer overflow detected" crash caused by incorrect JACK client name size limit

- src/g_canvas.c
The cursor is grabbed when Pd expects that a canvas is going to be created, but if `binbuf_read` fails, `proc pdtk_canvas_new` won't get called and the cursor won't be released.
> Release cursor if binbuf_read fails

- portmidi/Makefile.am
On linux:
```bash
./configure --disable-oss --enable-portmidi
make -j $(nproc)
```
fails.
Reason: `libportmidi.a` is missing the compilation of `finddefault.c`
> add finddefault.c to libportmidi.a

- src/g_array.c
> Draw array name when creating a garray

- src/g_clone.c
- src/g_editor.c
- src/g_graph.c
After creating a cloned instance, the reference to its parent canvas is currently cleared:
https://github.com/pure-data/pure-data/blob/80929213b540af1ba12c2c8abd7a58d0c1eb2204/src/g_clone.c#L213
This PR proposes to keep this `gl_owner` reference intact, and use glist's field `gl_isclone` instead for discriminating clones when needed.
It allows a clone instance to behave just like any abstraction, and in particular it makes possible to:
- resolve pure-data/pure-data#929 and fix pure-data/pure-data#410 (i.e clone cannot reliably use parents search paths)
- find the parent of the clone, through menu `Window / Parent Window`
- allow `[pdcontrol]` to retrieve parents information through `[dir N(` and `[args N(`
I basically replaced:
`if (x->gl_owner)`
with: 
`if (x->gl_owner && …
> keep parent canvas referenced from cloned instance

- src/g_all_guis.c
IMO it's time to give up retro-compatibility to Pd <= 0.47 by default, so that iemguis colors can be saved using full resolution hex-symbols.
e.g: instead of saving vslider like this:
`#X obj 96 97 vsl 15 128 0 127 0 0 empty empty test 0 -9 0 10 -258113 -257985 -159808 0 1;
`
let's use:
`#X obj 96 97 vsl 15 128 0 127 0 0 empty empty test 0 -9 0 10 #fc0400 #f8fc00 #9c00fc 0 1;`
That was planned for 0.48 ;-)
> finally save iemguis colors as hex symbols

- doc/2.control.examples/16.more.arrays.pd
- src/g_array.c
- src/g_template.c
This PR adds the following messages for garrays:
* `[color <f>(` - set line/point color (in data structure color format)
* `[width <f>(` - set line/point width
* `[style <f>(`- switch between point, line and bezier style
* `[vis <f>(` - show/hide array. Very useful if there's more than 1 array in a graph!
I've documented these features in `2.control.examples/16.more.arrays.pd`.
Small example:
> [WIP] Array features: dynamically set color, width, style and visibility

- doc/2.control.examples/16.more.arrays.pd
- doc/5.reference/plot-help.pd
- src/g_array.c
- src/g_template.c
* add `-e [constant or field]` to `[plot]` to (dynamically) enable/disable mouse editing
* add `[edit <f>(` message to `t_garray` to enable/disable mouse editing
* add `[vis <f>(` message to `t_garray` to show/hide array
implements https://github.com/pure-data/pure-data/issues/839#issuecomment-566247716
This is particularly useful when dealing with several arrays in a single graph, because you can selectively show/hide resp. enable/disable them.
> array editing features

- src/m_class.c
- src/m_pd.h
- src/s_audio.c
- src/s_audio_alsa.c
- src/s_audio_jack.c
- src/s_audio_mmio.c
- src/s_audio_oss.c
- src/s_audio_pa.c
- src/s_file.c
- src/s_inter.c
- src/s_main.c
- src/s_midi.c
- src/s_midi_oss.c
- src/s_midi_pm.c
- src/s_path.c
* add `t_loglevel` enum for `verbose()` in `m_pd.h`.
* replace all `verbose(1, ...)` calls with `verbose(PD_VERBOSE, ...)`
* replace all `if (sys_verbose) post(...)` occurences with `verbose(PD_VERBOSE, ...)`
> improve (verbose) logging

- src/s_main.c
since 95b614656cd62214d6779014e5173d8af697814b, the help browser doesn't display `extra` paths content anymore.
this is because  `s_main::sys_main()` first calls `s_inter::sys_startgui()`, which calls `s_inter::sys_do_startgui()` which then calls `s_path::sys_set_extrapath()` ( which sends the extrapath to GUI), before it calls `s_main::sys_afterargparse()` which calls `s_path::sys_setextrapath()` (which initializes the extrapath for the OS).
This PR just makes `sys_main()` calling `sys_afterargparse()` before `sys_startgui()`.
> restore sending extra path to help browser

- extra/pd~/pdsched.c
It would get the wrong number of channels because of a typo.
> fix crash in pd~ subprocess

- src/s_print.c
Unlike `verbose`, `logpost` and `startlogpost` wouldn't filter verbose messages.
Fixes https://github.com/pure-data/pure-data/issues/1420
> only print/send verbose messages if sys_verbose is true

- src/m_class.c
Fix `t_methodentry` bug introduced by using `unsigned char` instead of `t_atomtype` in this commit https://github.com/pure-data/pure-data/commit/0a727e594ffa4a85f2c3c8c18d51730ffcce160b. 
The methods' arguments are not well forwarded in `pd_typemess ()` because of the type of `me_arg` mismatches with the structure.
The bug is really annoying because when opening a patch the connection cannot be created, etc.  
I don't know why the bug doesn't seem to happen in Pd 0.52.0 (this might be related to my compiler - XCode 13.0 - AppleClang 13.0.0.13000029). 
I tested the fix using PDINSTANCE=1 (for Camomile) but  it should also work with PDINSTANCE=0.
> fix t_methodentry bug introduced by using unsigned char instead of t_atomtype

- doc/5.reference/symbol-help.pd
Deleted a duplicated (and strangely enough) not terminated in semicolon text line.
> [documentation] Remove duplicated strange comment line from symbol-help.pd

- src/d_filter.c
- src/d_osc.c
`x_ctl`'s only job is to point back to `x_cspace`. Instead we simply push the address of `x_cspace` to `dsp_add`.
> remove redundant pointer member in filter objects

- src/x_misc.c
This PR makes [cputime] work again on Windows. It was showing a 'couldn't create...' when opening 'list of objects'. Not sure which commit broke it.
Note: it still have the old behavior that gives values only when DSP is on (or only the very first time a bang gets in the right inlet if this was banged prior to any left bang).
> [cputime] and Windows

- src/g_text.c
this PR fixes bad gatoms' label font size when the canvas is zoomed-in, see:
https://lists.puredata.info/pipermail/pd-list/2021-11/130208.html
> fix the gatom's label font size when zoomed in

- src/g_editor.c
There is one behavior in the Pd interface that drives me actually insane -- I mean, occasionally shouting/screaming at the computer when it's requiring extra steps just to move an object around.
And that is: When you drag a single object on the canvas, and release the mouse button, it enters object-edit mode (to edit the text in the object).
From a UI design perspective, this is... baffling. You're either editing the object (click) or moving it (drag). When you're editing it, you're not moving it; when you're moving it, there's no justification to assume that the user means to edit. I can't think of any UI design principle that would call for these use cases to be intermixed.
The fix appears to be simple: A flag to detect whether the mouse has moved or not already exists! It's just not …
> g_editor: Don't enter object-edit mode after dragging an object

- tcl/helpbrowser.tcl
This PR addresses a couple of issues found on macOS for the help browser in Pd-0.52-0test2:
* browser list boxes (columns) not fully refreshing their contents on navigation
* browser complaint about undo/redo events
System tested: macOS 11.6.1
It looks like changes in Tk 8.6.12 may have affected the Tk idle timing, so forcing via `update idletasks` ensures the listbox display is refreshed.
For the binding, I'm just catching CMD+z and CMD+Z (aka SHIFT-CMD-z) but perhaps there is a better place or way to do this?
> helpbrowser fixes for 0.52-0test2

- src/s_audio.c
While working with LibPd, I noticed that its `PdBase::init` function was completely ignoring all of its parameters and falling back to default values. This is the simplest solution I could come up with to fix that. We just need to tell `sys_get_audio_settings` that audio settings were already initialized in `sys_set_audio_settings`
> Fixed bug where LibPd was ignoring init parameters

- .github/workflows/puredata.yml
yet another CI provider...
the reason to use this one is mainly because we get instant feedback in PRs of whether the build actually succeeds (e.g. things like #1495 should be really easy to catch with this)
this (again) uses an external workflow definition so we can adapt to changes in the infrastructure without bothering with Pd's repository.
> [ci] add GitHub workflow

- src/x_interface.c
Since the merge of #836, the [print] output is still prefixed with `verbose(2):` when using libpd mutli-instance printhooks.
This is a fix.
> [print]: fix avoiding 'verbose(2)' when using a printhook

- INSTALL.txt
- doc/1.manual/x6.htm
hello, just learning how to compile pd on windows 10, and in both instructions about mingw it says to install pkgconfig, but trying that gives me:
~~~
$ pacman -S pkgconfig
error: target not found: pkgconfig
~~~
changing it to pkg-config it worked: 
~~~
$ pacman -S pkg-config
resolving dependencies...
looking for conflicting packages...
Packages (1) pkg-config-0.29.2-4
~~~
So I changed both INSTALL.txt and x6.htm, hope this is ok
> Changing pkgconfig to pkg-config on windows mingw building instructions

- mac/patches/tk8.6.12_NSBitmapFormatAlphaFirst.patch
This is a backport of a build-fix for Tk-8.6.12: https://github.com/tcltk/tk/commit/e3db95d5882e8cf0750989b7311f69c3fdabf065, that allows running `mac/tcltk-wish.sh 8.6.12` on older OSX-versions.
so far i've tried:
- OSX-10.7: the build now fails elsewhere
- OSX-10.8: the build succeeds (but it's not possible to use `-universal` to create an i386/amd64 binary; I don't think there is any necessity for i386 builds)
i only have access to an OSX-10.7  and an OSX-10.8 machine remotely, so I cannot test whether the resulting binary actually works.
However, running ` ./Wish-8.6.12.app/Contents/MacOS/Wish` does not crash (but it just waits forever), which i think indicates that nothing is fundamentally wrong. (if i run the same on command with the universal binary compiled on macOS-11 provided by …
> Fix compilation of Tk-8.6.12 on OSX<10.12

- doc/Makefile.am
- src/s_audio_jack.c
if JACK dynamically changes the samplerate, we need to update the internal sample rate.
this PR does this by automatically restarting the DSP (but only if DSP is currently ON and the srate actually changed).
- Pd/JACK runs at 44kHz; DSP is on; [osc~ 440] sounds at 440Hz
- JACK dynamically switches to 48kHz
- Pd's output pitches up to 479Hz
- Pd prints "partial read" to the terminal.
- turning Pd's DSP off and on again, pitches the output back to 440Hz
that's a bit weird.
with the new behaviour the samplerate switch is *almost* seamless.
There's a short glitch when switching, because the samplerate change notification is asynchronous; therefore thus the output will be detuned for a couple of ms.
> Propagate changed samplerate from JACK, by restarting the DSP

- src/g_editor.c
- tcl/dialog_font.tcl
closes #1511
send the "dirty" message to the canvas from tcl in "apply" procs, instead of checking in canvas_font
> set dirty flag from font dialog only

- src/g_canvas.c
- src/m_pd.h
This PR fixes a few irrelevant typos in comments in `g_canvas.c`.
(I noticed them looking for something else altogether, but why not fix them when I've already found them?)
> Fix typos in g_canvas.c's comments

- tcl/pdtk_canvas.tcl
win32: place the patch window in the current display if it was saved on an non-available xy position (eg. in a multi-monitor setup).
Closes: #1619
> win32: show patches saved outside available xy positions

- src/d_soundfile.c
* fix regression with `[readsf~]`: sending an `[open(` message while a stream is running causes the next stream to fail silently. This didn't happen in Pd 0.51 and before.
* fix possible race condition in `readsf_perform` and `writesf_perform`
* minimize critical section in EOF branch in `readsf_perform`
* cosmetic fixes
The first issue has bitten me recently in a rehearsal. While looking at the code I found a few other possible race conditions, hence this PR.
> readsf~/writesf~ fixes

- src/d_ctl.c
- src/d_ugen.c
hey,
while studying the code I realized that [sig~] never used its vectorized `sig_tilde_perf8()` function.
Moreover, both `sig_tilde_perform()` and `sig_tilde_perf8()` were (privately) defined twice, in both `d_ctl.c` and `d_ugen.c`, and a public `dsp_add_scalarcopy()` already existed, which takes care of calling the `perf8()` when the vector size is a multiple of 8.
So here is a simplification (and a fix...) for [sig~] that calls `dsp_add_scalarcopy()` and removes duplicate sig_perform functions.
> [sig~] use the vectorized perf8 version

- src/x_connective.c
currently, nothing is output, this fixes it
closes https://github.com/pure-data/pure-data/issues/1678
> fix [route] rejected output for bang input with float arguments

- doc/6.externs/makefile
- don't pretend to build i386 or x86-64 binaries (as we can't control this)
- use .pd_linux as a generic file extension
- drop the "pd_linux32" target
- unconditionally build with "-fPIC" (it works everywhere)
- build with debugging symbols
- drop the "-Werror" flag as it fails builds with newer gccs.
Closes: https://github.com/pure-data/pure-data/issues/1722
> fix doc/6.externs build for Linux

- src/m_obj.c
This fix correctly fixes a crash when sending the message "signal" to signal inlets, which is caused by access to the iu_symto value of the inletunion union when it is not correctly defined.
It is intended to correct 6aaa6f7d2c5133b848e5fcd66d7f030eb79b85fb which seems to have been applied to the wrong place (where iu_symto is not accessed). *This* fix looks for places where the incoming symbol matches the inlet symbol and is also "signal" and avoids the dereference at that point. The crash itself is caused by a dereference that is typically a NULL and thus typically the code ends up calling through to a point where that NULL symbol is then dereferenced in order to print an error to the console, at which point pd crashes.
The crash and fix can be tested with the attached patch. Before …
> Fix signal message crash

- extra/bob~/bob~.c
As it is, it fails if one changes the definition of `FLOAT`
> bob~: outstate should be FLOAT not double

- src/g_editor.c
- src/g_text.c
- src/s_print.c
- tcl/pd_deken.tcl
from the announcement on Pd-list
deken-plugin ("Find externals" within Pd)
=========================================
- brand-new excel-like interface
- sort by library/version/uploader/date
- quick link from a package to it's deken homepage (which features objectlists and more)
- simple selection of multiple packages
- INSTALL button
- watch the installation as it unfolds
- proper menu for installing pre-downloaded package files
- fast SHA256 verification on all platforms
- option to uninstall packages
- proper menu for proper ties
- advertise https://deken.puredata.info/
- better feedback if search returned no result
- tooltip
- balloons
- improve guessing of deken architecture
- fix version sorting
- fix all bugs
- fix some more bugs
- implement many bugs
additionally, this PR allows …
> Update deken to 0.9.4

- linux/release-checklist.txt
the damn tag to upload to github this time.
> add a snidery about taggery to release-checklist to see if I can get

- tcl/pdtk_canvas.tcl
Fix window positioning according to discussion in #1805.
Windows that were saved with negative positions (caused by multiscreen setups with a secondary screen on the left or on top of the primary screen for example) were placed in an invisible area on reload because the wrapping of the position did not consider legitimate negative coordinates.
This PR is to be merged into `develop` branch.
Closes: #1805
> Bugfix/tcl window positioning (#1805)

- tcl/dialog_iemgui.tcl
This fixes the mechanism for composing custom colors in iemguis as reported in #1828.
When trying to create a custom color in the iemgui properties, Pd-0.53-0 returns an error (confirmed for MacOS and Win10), which is solved here by the changed tcl line as discussed in the issue.
This PR is to be merged into develop branch.
Closes: #1828
> Fix error when composing custom color in iemguis (#1828)

- src/g_slider.c
Fix #1941 by making sure that `x->x_val` is never negative.
> address slider handle out-of-bounds problem

- src/g_editor.c
people keep complaining about not being able to create a connection on HiDPI screens, because the hotspot for starting a connection is too small.
while "intelligent patching" addresses some of these problems (e.g. by being able to <kbd>Tab</kbd>-cycle the outlets until you find the one you want), it requires a change in workflow.
This PR simply enlargens the outlet hotspot:
- the height of the hotspot is raised to the double size of the outlet. however it will not cover more than ¼ of the entire object height (typically this means that the height of the hotspot is ¼ if the object height)
- the width of the hotspots is no longer limited. instead you always get the *nearest* outlet (similar to how inlets are currently selected)
- the pending connection line will always start in the center …
> enlarge hot area for outlets

- src/s_main.c
This allows to open patches with creation arguments.
Syntax: `-open-with-args <patch> <arguments>`
Multiple arguments have to be enclosed in quotation marks.
Example:
`pd -open-with-args foo.pd "bar baz 1 2 3"`
Simple test patch: [foo.zip](https://github.com/pure-data/pure-data/files/4758116/foo.zip)
Closes https://github.com/pure-data/pure-data/issues/1058
---
Of course, you can also open multiple patches:
`pd -open-with-args patch1.pd "1 2 3" -open-with-args patch2.pd "foo bar baz"`
---
Or you can load several patches with the same arguments:
`pd -open-with-args "patch1.pd:patch2.pd" "1 2 3"`
NOTE: the colon seperator is *not* a new feature. (On Windows you have to use a semicolon, instead.)
> add "-open-with-args" command line option

- Makefile.am
- configure.ac
- font/Makefile.am
- mac/osx-app.sh
- msw/build-nsi.sh
- msw/msw-app.sh
- portaudio/Makefile.am
- src/Makefile.am
- src/d_fft.c
- src/m_glob.c
- src/m_pd.h
- src/s_audio.c
- src/s_audio_pa.c
- src/s_loader.c
- src/s_main.c
- src/s_midi.c
- tcl/dialog_startup.tcl
- tcl/pd-gui.tcl
this PR deals with the idea that both a single-precision Pd and a double-precision Pd can be installed at the same time (with the same package/installer/...).
The PR mostly fixes bugs with the buildsystem, that prevent the creation of co-installable binaries.
from a "new feature" perspective, I think the sole new feature is that 
- the GUI now has a preference to select which variant is to be launched
- and some accompanying code to actually launch that variant (either "pd" or "pd64")
- this "new feature" has been added as the last commit (https://github.com/pure-data/pure-data/pull/1995/commits/4036292a69b6c598408cf07df54a4780103413cf), so if it is unfit for inclusion in Pd-0.54-0, it can be easily left out)
after a lot of discussing and experimenting (see below), it also turned out that …
> Co-installable double-builds

- src/d_ugen.c
When a switched-off canvas is reblocked and switched on again, we make sure that the block prolog phase is in sync with the inlet prolog and outlet epilog phase.
Closes https://github.com/pure-data/pure-data/issues/2136
> Fix `switch~` + reblocking

- src/x_gui.c
- tcl/pdtk_canvas.tcl
- tcl/pdwindow.tcl
- tcl/wheredoesthisgo.tcl
On Windows, the Tk dialogs are non-modal which means that they can get hidden by the parent window and the user can open the same dialog more than once. This PR makes those dialogs window-modal, so they always stay on top of the parent. They only block interaction with the parent window, other windows are not affected. As a long-time Windows user, this is the behavior I would expect of such dialogs. Fixes https://github.com/pure-data/pure-data/issues/751
I've tested on OSX 10.11 and Debian 9 + GNOME and there's practically no difference in behavior because dialogs already seem to be *application-modal* by default. There's one subtle difference on OSX: dialogs show up in front of the parent window, which I find rather nice, but I'm not a regular OSX user (@danomatika probably has something …
> make openpanel/savepanel + "save as" dialogs window modal

- po/de.po
I've fixed a few small typos.
(If you insist, I can try and go through Weblate instead of this "direct" PR :-)
> Fix typos in German translation, de.po

- src/x_file.c
- Closes: https://github.com/pure-data/pure-data/issues/1665
- Closes: https://github.com/pure-data/pure-data/issues/2008
- Closes: https://github.com/pure-data/pure-data/issues/2080
(now all paths referencing "real" files will expand `~/` as the user's home directory; the exception are the string operations as found in `[file split]` and friends)
i haven't updated the documentation yet, leaving this for the `documentation` branch :-)
> Various minor improvements to [file]

- extra/pd~/pd~.c
- src/g_all_guis.c
- src/g_canvas.c
- src/m_binbuf.c
- src/m_class.c
- src/m_obj.c
- src/m_private_utils.h
- src/s_audio_mmio.c
- src/s_audio_pa.c
- src/s_file.c
- src/s_inter.c
- src/s_loader.c
- src/s_print.c
- src/s_stuff.h
- src/x_file.c
- src/x_gui.c
Currently, we define `snprintf` as `_snprintf` when building with MSVC. However, `_snprintf` is *not* a drop-in replacement for `snprintf`! Most importantly, it does not null-terminate the output buffer on truncation! Also, it outputs -1 instead of the number of required bytes.
Note that the UCRT (universal C runtime), provided for Windows 10 and above, actually contains a C99-conforming `snprintf` function. When targetting older systems, MSVC would just define `snprintf` as `_snprintf`. See https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/snprintf-snprintf-snprintf-l-snwprintf-snwprintf-l?view=msvc-170.
On MinGW the situation is also a bit complicated, as it traditionally uses the old `msvcrt.dll`, which only has the non-conforming `_snprintf`. Some versions define …
> Safe cross-platform `snprintf` and `vsnprintf` alternative

- src/m_class.c
- src/m_pd.h
On Windows it is not possible to 'properly' export a thread local variable from a DLL. MinGW can do it, but the resulting symbol (`__emutls_v.pd_this`) is not portable and certainly not understood by MSVC. As a consequence, Windows externals built with  `-DPDINSTANCE` cannot really use `pd_this` - unless both the external and the host is built with MinGW.
The solution is to access `pd_this` via a function call, for this I've added a new API function `pd_getinstance()`. For externals, `pd_this` is now a macro for `pd_getinstance()`. Internally, we directly access 'pd_this', but we don't try to export it.
On other platforms, `pd_this` is now properly marked `EXTERN`.
> fix `pd_this` on Windows

- doc/1.manual/x2.htm
fixes according to https://github.com/pure-data/pddp/issues/190#issuecomment-2024495886
* 4 typos fixed
* consistent quotes for id- and href-attributes
* 2 links corrected
> typos, links, ids consistently with quotes

- doc/3.audio.examples/D12.sampler.bis.pd
The comment had an error in describing the passage of data from a [route] object to [pack] via a $2 message.
The previous comment claimed $2 contained amplitude which gets packed into the note data, but actually $2 contains the poly voice number. I adjusted the comment to reflect that:
Old:
"Otherwise, the "$2" retrieves the nonzero amplitude for a note-on message, to which we add all the other parameters and route to the appropriate voice inside \[clone\]."
New:
"...Otherwise, the "$2" retrieves the voice number from \[poly\] which gets packed in with the note data and routed to the appropriate sampvoice2 \[clone\]"
@porres this is attempt 2 at this pull request: https://github.com/pure-data/pure-data/pull/2255
> Minor change to comment on D12.sampler.bis.pd eample patch

- doc/3.audio.examples/G09.pitchshift.pd
The comment beginning with "The 'window size' is the total trajectory" was duplicated.
> Remove duplicate comment from G09.pitchshift.pd

- src/g_canvas.c
- src/m_pd.c
- src/m_sched.c
- src/s_audio.c
- src/s_audio_jack.c
- src/s_audio_pa.c
- src/s_audio_paring.c
- src/s_audio_paring.h
- src/s_file.c
- src/s_inter.c
- src/s_main.c
- src/s_midi.c
- src/s_stuff.h
- src/z_libpd.c
General:
* `glob_exit` breaks from the scheduler loop, instead of calling `exit`, and thus allows for proper cleanup in `sys_main`.
* `sys_main` calls a new function `pd_term` (counterpart to `pd_init`) before returning. Currently, `pd_term` just destroys the root canvases, but LATER it should free *all* resources. Ideally, Pd should not leak any memory on shutdown.
* fix `audio_shouldkeepopen` for the case where no audio backend has actually been opened (yet). Now `pd -jack` immediately connects to the Jack server; before you had to turn on DSP first.
* if the user switches backends or applies audio settings, only open audio if DSP is on or audio should be kept open
* only derive sleep grain from `sys_schedadvance` if we are in the polling scheduler and DSP is turned on, otherwise use a …
> improve scheduler

- src/d_array.c
This PR makes the onset inlet for `tabread4~` signal rate. For example, this would be particularly useful for sample-accurate granular synthesis, where you could use `[vline~]` for the onset. (Currently, I have to use the [undocumented!] `tabread4~~` object in `zexy` for my granular synthesis abstractions, which I find a bit silly.)
I think there is no real reason to restrict the onset inlet to control rate - except for efficiency. However, the overhead of the additional (cached!) memory access should be tiny compared to the actual interpolation math.
If efficiency is indeed a concern, I could add a scalar version (using `CLASS_NOPROMOTESIG`)
> tabread4~: make onset inlet signal rate

- src/x_misc.c
[oscparse] always parses addresses as symbols, even if they look like floats, which make it really hard to use [route]. I propose a flag that turns addresses that look like floats into floats.
We also add an outlet that gives the index in the output list that splits the address from the data
closes https://github.com/pure-data/pure-data/issues/1299
also closes https://github.com/pure-data/pure-data/issues/1858
> [oscparse] improvements

- mac/osx-app.sh
- tcl/dialog_find.tcl
- tcl/dialog_font.tcl
- tcl/dialog_iemgui.tcl
- tcl/dialog_path.tcl
- tcl/dialog_startup.tcl
- tcl/pd-gui.tcl
- tcl/pd_docsdir.tcl
- tcl/pd_guiprefs.tcl
- tcl/pd_i18n.tcl
- tcl/pd_menucommands.tcl
- tcl/pdtk_canvas.tcl
- tcl/pdtk_textwindow.tcl
- tcl/pdwindow.tcl
- tcl/wheredoesthisgo.tcl
this PR attempts to fix some issues with the i18n framework within Pd.
the original code has convoluted (and incorrect) platform-specific attempts to get the correct property stating the system's chosen language (Windows registry, macOS defaults, `$env(LANG)`...).
however, the `msgcat` extension (which handles translations), can also provide this information (and more correctly). so the new code just *uses* these defaults (if no override is specified)
- Closes: https://github.com/pure-data/pure-data/issues/2270
macOS's System Settings allow selecting a language for a specific app.
For this to work, the app has to declare which languages it supports.
this was disabled by 6b42a26d52708a4cc8df18f4901bfa48fc9fbb66 with the following comment:
> commented out for 0.48-1 because it seems to …
> improve language detection

- tcl/pdtk_canvas.tcl
Changes canvas positioning for Windows users once more according to discussion in https://github.com/pure-data/pure-data/issues/2194.
This replaces the current logic where positions get wrapped with a more predictable solution that keeps the canvas inside screen bounds (these bounds also apply for multi-screen setups and can have a negative origin)
This PR is to be merged into develop branch.
- Closes: https://github.com/pure-data/pure-data/issues/2194
> Windows: restore canvas inside screen bounds

- src/g_editor.c
- src/m_glob.c
- src/m_imp.h
- src/s_inter.c
* the "quit" message force-quits Pd, like it did before Pd 0.55
* the (new) "exit" message exits from the scheduler and quits gracefully (but only after the current clock tick has finished)
Closes https://github.com/pure-data/pure-data/issues/2339
> restore old behavior of "quit" message and add new "exit" message

- src/s_inter_gui.c
This avois errors when building with clang on NixOS.
Excerpt of the compile errors this avoids: 
```
/nix/store/svf4zn4qg9lsxfn4znyxk7nl80hlmgpm-clang-wrapper-17.0.6/bin/clang -DHAVE_ALLOCA_H=1 -DHAVE_ENDIAN_H=1 -DHAVE_LIBDL=1 -DHAVE_UNISTD_H=1 -DLIBPD_EXTRA=1 -DPD=1 -DPDINSTANCE=1 -DPDTHREADS=1 -DPD_INTERNAL=1 -DQT_DISABLE_DEPRECATED_BEFORE=0x0605ff -DQT_NO_KEYWORDS -DUSEAPI_DUMMY=1 -I/build/score-master/build/libpd -I/build/score-master/3rdparty/libpd -I/build/score-master/build -I/build/score-master/3rdparty/libpd/libpd_wrapper -I/build/score-master/3rdparty/libpd/pure-data/src -isystem /build/score-master/3rdparty/libossia/3rdparty/nano-signal-slot -isystem /build/score-master/3rdparty/libossia/3rdparty/readerwriterqueue -isystem /build/score-master/3rdparty/magicitems/include …
```
> Fix build when dprintf is defined as a macro

- src/m_private_utils.h
- src/s_audio_jack.c
- src/s_audio_pa.c
- src/s_audio_paring.c
- src/s_audio_paring.h
- src/x_vexp.h
- src/x_vexp_fun.c
- src/z_ringbuffer.c
- src/z_ringbuffer.h
Since https://github.com/pure-data/pure-data/commit/cad91dc791c7b17972d4d508f6bf6a93f1ff0613 expr supports a number of string functions.
Unfortunately, some of these functions are named differently on Visual Studio.
This PR does the olde define magic to use usable versions of `snprintf()`/`strcasecmp()`/`strcasecmp()`
Closes: https://github.com/pure-data/pure-data/issues/2406
> expr: MSVC compat for snprintf/strcasecmp/strcasecmp

- doc/5.reference/list-help.pd
- src/d_soundfile.h
- src/s_loader.c
- src/s_print.c
This fixes an oversight when a new function was added to s_loader.c: iOS doesn't support dlopen, so we need to wrap it with `HAVE_LIBDL`.
> fix libpd ios build by wrapping dlopen call with HAVE_LIBDL

- configure.ac
- extra/bonk~/bonk~.c
- extra/sigmund~/sigmund~.c
- src/d_soundfile.h
- src/s_inter.c
- src/s_net.c
- src/s_stuff.h
- tcl/pdtk_canvas.tcl
(just merged, and here it is again)
this is the permanent branch `develop` that only gets curated, small, no-brainer changes that can be easily merged into master at any time.
(as a general rule-of-thumb we shouldn't include changes to `.pd`-files (including help patches!) in this PR, as it is just too easy to end up with unresolvable file conflicts.).
it supersedes https://github.com/pure-data/pure-data/pull/2467
---
- Closes: https://github.com/pure-data/pure-data/issues/2335
- drop (some) unnecessary tests from `configure`
- add some more checks for available types to `configure`
- fix include-file precedence for `alloca()` in *bonk~* and *sigmund~*
- include `<stdarg.h>` in headers that use `va_list` types (for variadic functions)
- allow building on (Open)Solaris/IllumOS
>  stable development branch

- src/d_soundfile.c
adds warning for unparseable elements when loading ASCII data.
suggestion came up in #2505 - more specifically https://github.com/pure-data/pure-data/issues/2505#issuecomment-2590440250
> soundfiler: report parse errors when loading ascii file

- mac/tcltk-wish.sh
- msw/build-nsi.sh
- msw/msw-app.sh
- msw/tcltk-dir.sh
This PR includes a number of fixes for building Pd for Windows-on-arm, as well as for building TclTk-9.0
So far, no changes to the source code have been required :-)
However, there are a few amendments to the build-scripts in the `msw/` subdirectory:
- `tcltk-dir.sh`
- allow building on MSYS2/clang-aarch64 (and other MSYS2 variants)
- `msw-app.sh`
- fix stripping of binaries, e.g.
-  do not fail if there are some wrong-arch binaries that cannot be stripped
- do not strip TclTk binaries (from the pdprototypes), as TclTk-9.0 now embeds the stdlib in the DLL as a zip-package, which would get stripped away, leading to an unusable TclTk engine.
- `build-nsi`
- recognize arm64 as a 64bit architecture
- improve architecture detection in general
and a few more in the `mac/` subdirectory:
- …
> Fixes for arm64 on Windows and for buliding TclTk-9.0

- src/m_sched.c
- src/s_audio.c
- src/s_audio_jack.c
- src/s_audio_pa.c
Since Pd 0.55, `sys_reopen_audio()` does not immediately (re)open the audio device -- which would deadlock in the callback scheduler --, instead it posts a message to the scheduler and the device is only (re)opened at the beginning of the next scheduler tick.
Unfortunately, this means that for the remaining tick Pd objects still see the old samplerate, which breaks patterns like these:
This happens, for example, when you start Pd with the Jack backend and with a samplerate other than 48000 (= the default samplerate). It also happens when you change the samplerate in the audio settings.
---
If we are in the main thread, we can safely close and (re)open the audio device *synchronously*. This makes sure that objects immediately see the actual samplerate. For example, the sample rate might …
> Try to open audio device synchronously

- tcl/pdwindow.tcl
this adds "right click" via ctrl+click via `<Control-Button-1>` in the Pd window for macOS similar to the canvas window behaviour:
https://github.com/pure-data/pure-data/blob/eaaf7991748a71412686a6d4a52972d67c4d4933/tcl/pd_bindings.tcl#L299-L300
> support ctrl+click in pd window on macos

- tcl/pdwindow.tcl
support right click on error messages in Pd Window on macOS with Wish9.x
> support tcl9 for pd window right click on macos

- src/m_binbuf.c
In the event that the first dollar sign we come across isn't related to a dollarsym atom, we need to keep looking. Otherwise, there will be inconsistencies between a patch's state upon saving, and its state after closing and re-opening.
Example: in the message "$$1", the 1st $ is actually a dollarsym's prefix, so we need to check the 2nd $ as well.
Here is a video showing a before and after of this PR:
https://github.com/user-attachments/assets/41db09b5-5ce1-4f67-a648-7bdc5dc0cc4c
> Check for multiple dollar signs in binbuf_restore

- src/m_binbuf.c
- src/m_pd.h
this PR adds basic support for Pd-files that contain a shebang.
Closes: https://github.com/pure-data/pure-data/issues/672
a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) is a special character sequence at the beginning of an executable file, that tells the program loader which interpreter to use to execute the file.
a `.pd` file with a shebang could be used as a standalone script.
e.g. consider a Pd file `hello.pd`:
```pd
#!/usr/bin/env -S pd -nogui -open
#N canvas 2655 476 280 264 12;
#X msg 142 143 world;
#X obj 142 168 print hello;
#X obj 72 91 loadbang;
#X obj 72 123 t b b;
#X msg 72 148 \; pd quit;
#X connect 0 0 1 0;
#X connect 2 0 3 0;
#X connect 3 0 4 0;
#X connect 3 1 0 0;
```
when made executable (`chmod +x hello.pd`) you could simply run:
```sh
$ ./hello.pd
hello: …
```
> shebang support

- doc/1.manual/resources/chapter5.htm
- doc/1.manual/resources/pdmanual.css
this PR uses HTML tags and classes in the release-notes (`doc/1.manual/resources/chapter5.htm`), so they become parseable.
the motivation behind this is to be able to transform the release-notes to other formats, most importantly the [appstream metadata](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html).
the main difference is, that now instead of something like
```html
<P> ------------------ 0.53-2 ------------------------------
```
you have to write
```html
</section><section class="releasenote"><h4 id="0.53-2">0.53-2</h4>
```
while being there, i have cleaned up closing tags (that is: for every `<P>` tag, there is now a matching `</P>` tag).
i've also adjusted the CSS to render (almost the same), automatically adding the `---------` lines (actually, now it renders …
> parseable releasenotes

- tcl/pd_bindings.tcl
closes #2347
this fixes the macOS issue mentioned above where a `cmd`+`click` in another patch window changes the "interaction focus", but the previously focused window still looks like the one in focus and an actual focus change back to the front window requires a clicks outside and then inside the front window.
not sure if this is the proper way to fix this - but it does solve this rather annoying behavior by forcing the window focus for modifier+click.
currently only tested on macOS. ~~maybe this should be macOS-only code, since it doesn't seem to cause issues on other systems?~~ EDIT: forced focus only happens on macOS now.
> handle focus switch for <Modifier-Click> (fixes macOS behavior)

- src/m_pd.h
- src/m_sched.c
- src/s_inter.c
Currently, there is no obvious and safe way for posting a message from a helper thread to a Pd object.
People sometimes try to execute code between a pair of  `sys_lock` + `sys_unlock`, but this can actually deadlock when you join the thread. The correct solution would be to implement your own thread-safe queue and poll it regularly with a clock; this is neither obvious nor trivial.
Therefore I propose the following API:
* `EXTERN void pd_queue_mess(struct _pdinstance *instance, t_pd *obj, void *data, t_messfn fn)`
This sends a message to a Pd object from another (helper) thread. `fn`will be called on the scheduler thread with `obj` and `data`.  If the message has been canceled, the `obj` argument is `NULL`; the function will still be called because it is reponsible for freeing the …
> new API functions for thread-safe messaging

- src/m_pd.c
- src/m_pd.h
The standard method for data sharing in Pd is to bind objects to symbols. Internally, objects call `pd_findbyclass` to get another object from a symbol. Since every symbol can be bound to multiple objects with the same name (but with different classes) the user needs to pass a pointer to the expected class (`t_class*`). This is all fine as long as all objects are defined in the same module (e.g. in the Pd core or in a single-binary-library). However, as soon as the objects live in different binaries, you run into problems because you need to share the class pointer across DLL boundaries, which turns out to be very tricky.
To solve this problem, I've introduced a new function called `pd_findbyclassname`. This is the same as `pd_findbyclass()`, except that you pass the class name instead of …
> add new API function `pd_findbyclassname`

- src/d_ctl.c
- src/d_misc.c
* `[print~]`: print multichannel signals:
```
<symbol>:
channel 1:
<data>
channel 2:
<data>
...
```
* `[snapshot~]`: handle multichannels signals by outputting a list
* `[sig~]`: multiple creation arguments generate a multichannel signal; each scalar value gets a float inlet.
> Some missing multichannel objects

- src/x_midi.c
These are my personal patches to the [poly] object. I've found them so useful that I think they could make it into Pd vanilla.
* dynamically set number of voices
if the new number is smaller than the old one, excess voices are flushed, 
otherwise existing voices are left untouched.
* dynamically enable/disable voice stealing
* add `[sustain <f>(` message which mimicks a piano sustain pedal. 
`[sustain 1(` - note-offs are sustained
`[sustain 0(` - all sustained notes are flushed
* add `[stack <f>(` message which enables/disables stacking of sustained notes of the same pitch
`[stack 0(` - can't sustain more than one voice of the same pitch (like a piano)
`[stack 1(` - sustain as many notes of the same pitch as you like (like many polyphonic synthesizers)
> [poly] features

- src/g_canvas.c
- src/g_clone.c
- src/g_editor.c
- src/g_readwrite.c
1. If a cloned abstraction is saved, Pd currently just remakes the corresponding clone object and restores the window of the previously save instance. This is not a real solution, as the current abstraction is fully reinitialized - which can be *very* annoying.
Instead we first try to update the clone object(s). This is done by reinitializing the canvases, without touching the currently saved abstraction! However, if the inlets/outlets appear to have changed, we refuse to update and rather remake the whole object.
Closes https://github.com/pure-data/pure-data/issues/495
2. If an abstraction is saved, Pd searches all canvases for other instances and remakes them. Now we extend this search to instances *inside cloned abstractions*. Otherwise, cloned abstractions would still contain outdated …
> More clone improvements

- tcl/pd_deken.tcl
https://github.com/pure-data/deken/commit/3e3e401acea46a174831a9d9a72a1017595335da
- fix SHA256 verification on windows (when using the certUtil tool)
- handle illegal installation directories
- try to create missing ones
- prompt if it is not actually a dir
- better handling of bad filenames (when installing a local .dek package)
Closes: https://github.com/pure-data/deken/issues/301
- improve package extration
- support zipfs (included in Tcl9.0)
- support untar (on Windows[sic]) which fixes installation of packages on managed Windows where the Windows 
Scripting Host is blacklisted
Closes: https://github.com/pure-data/deken/issues/303
- fix 0-permission files when unzipping with tcllib
Closes: https://github.com/pure-data/deken/issues/306
- when auto-uninstalling a library on re-install …
> Import deken v0.10.4

- src/d_array.c
- src/g_array.c
- src/g_canvas.c
- src/g_graph.c
- src/g_readwrite.c
- add a `visname` message to *garray* to hide the name
Closes: https://github.com/pure-data/pure-data/issues/2422
(this is automatically persisted, as the `hidename` flag has been there forever... Just without an option to set it)
- add a `keep` message to *garray* to set the "saveit" flag
Closes: https://github.com/pure-data/pure-data/issues/2428
- store the following properties when saving an array:
- `color`
- `width` (linewidth)
(they are only stored if compatibility is >0.52 where these messages were introduced)
Closes: https://github.com/pure-data/pure-data/issues/1838 (well partly, there's no corresponding properties dialog entry)
i think these properties are meant to be persistent (you typically either need them for an array or you don't, but not both)
the `vis` and `edit` …
> improve garrays: add message to hide name, save properties

- src/d_array.c
- src/g_array.c
This reverts parts of https://github.com/pure-data/pure-data/pull/2427 that attempted to fix https://github.com/pure-data/pure-data/issues/2533, specifically the following two commits:
https://github.com/pure-data/pure-data/pull/2427/commits/373df447046d54384bb2c208979ceabcc03b58ef
https://github.com/pure-data/pure-data/pull/2427/commits/03ccff4ca6110afcbce4c40ea773ff3b6e14c31c
First, this solution doesn't seem to work. If I rename a garray with "rename", any table DSP object, such as `[tabreceive~]`, that is bound to the old name just keeps referencing the same array.
Second, there is a severe problem with https://github.com/pure-data/pure-data/pull/2427/commits/373df447046d54384bb2c208979ceabcc03b58ef: by setting `garray_usedindsp` we cannot resize the garray anymore without causing a …
> Trigger error message in table DSP object if table has been renamed

- src/d_array.c
The "set" message can now resize the DSP array vector. This causes a DSP update if the number of channels has changed. Passing an empty list only "unsets" the arrays.
`[tabwrite~]` and `[tabsend~]`: write input channels to subsequent tables; excess channels or excess tables are ignored.
`[tabplay~]` and `[tabreceive~]`: the number of output channels equals the number of arrays.
`[tabread~]` and `[tabread4~]`: the number of output channels is the maximum of the number of arrays and the number of channels of the input signals. This means you can:
1. read multiple tables with a single-channel phase input (e.g. playback a multichannel sample)
2. read a single table with a multi-channel phase input (e.g. apply a waveshaping table to all channels)
3. read a multi-channel table with a …
> allow to change the number of channels in table DSP objects

- src/g_canvas.h
minor API clean-up (noticed by @porres)
`rtext_height()` and `rtext_width()` were removed in 1b928e67 and replaced with `rtext_getrect()`.
> remove orphaned rtext_height() and rtext_width() declarations

- src/g_editor.c
fix object renaming through properties by storing and reusing `x->gl_owner`
closes #2636
> fix object renaming by storing and reusing x->gl_owner

- src/g_bang.c
- src/g_canvas.c
- src/g_editor.c
- src/g_graph.c
- src/g_mycanvas.c
- src/g_numbox.c
- src/g_radio.c
- src/g_scalar.c
- src/g_slider.c
- src/g_toggle.c
- src/g_vumeter.c
Fixes some issues with Pd's colors. This is a reboot of https://github.com/pure-data/pure-data/pull/2646
It's made simpler and packed into 3 commits:
------
- closes https://github.com/pure-data/pure-data/issues/2663
- partially closes items in https://github.com/pure-data/pure-data/issues/2642
> Fix Pd colors

- src/g_all_guis.c
- src/g_all_guis.h
- src/g_bang.c
- src/g_canvas.c
- src/g_canvas.h
- src/g_editor.c
- src/g_graph.c
- src/g_mycanvas.c
- src/g_numbox.c
- src/g_radio.c
- src/g_rtext.c
- src/g_scalar.c
- src/g_slider.c
- src/g_template.c
- src/g_text.c
- src/g_toggle.c
- src/g_vumeter.c
this builds on (and includes) https://github.com/pure-data/pure-data/pull/2668/
but adds the following:
- use `unsigned int` for the internal representation of colors (rather than a symbol) (ffafeaa10526466e912b6dd6ce5d5876cb5ae633)
- as a consequence, we can get back to using `k` (the *color* specifier) in `pdgui_vmess()` for sending colors to Pd-GUI again (rather than a weird mixture of `k`, `s` (escaped strings) and `r` (raw strings).
- the 2nd commit (929212f9b831e58c9d37edd7dafb56ee9ed38521) allows iemgui's to understand a color `default` which just uses whitish for the background, and black for label/foreground.
- this is mean **only** as a smallish change to allow future versions of Pd to use the `default` color in a more meaningful way (as in: use the colors from Pd's color …
> Fix Pd colors a bit more

- src/s_audio.c
- src/s_midi_pm.c
- tcl/dialog_audio.tcl
this makes the "Rescan Devices" button part of the audio settings frame. that way, the layout is not as nice, but the button is present in the audio dialog and the tabbed preferences for audio.
the ui update mechanism is obviously (and unfortunately) more complex here since it checks what to update on the tcl side (instead of just calling `glob_audio_properties(0)`).
* closes #2684
* makes sure that we don't reinitialize portaudio in "callback" mode when audio is running (would deadlock)
* prevents the console flooding reported in #2683 (but doesn't solve the device list update issue)
> Add "Rescan Devices" button to tabbed audio preferences

- src/g_editor.c
- tcl/pdtk_canvas.tcl
This applies Pd's foreground color to the text caret.
Right now it defaults to black, so it becomes invisible with a black background
This issue is mentioned amongst others in https://github.com/pure-data/pure-data/issues/2674
-------
It was a small change that required also sending THISGUI->i_foregroundcolor (besides THISGUI->i_backgroundcolor) to "pdtk_canvas_new" and use "-insertbackground" to configure it
> fix text caret with foreground color

- src/g_template.c
this is an attempt to fix the remaining issue for #2589 mentioned in https://github.com/pure-data/pure-data/issues/2589#issuecomment-3129369190
it consists of 2 commits to:
* consider `drawtext_isvisible` for `drawtext_getrect`
* extend rect to left by label size (feels a bit hacky)
@millerpuckette not sure if this is the right approach - maybe it's also not too bad to omit the labels for selection?
> Fix selection rectangle for data objects with invisible text or labels

- src/g_editor.c
- tcl/dialog_canvas.tcl
properly handle (and preserve) dollargs entered in properties dialog of abstractions.
(not sure if handling more characters might be desirable - but this covers the most relevant case)
opening this PR after quick coordination with @Ant1r - see https://github.com/pure-data/pure-data/pull/2723#issuecomment-3166805844
closes #2720
> escape dollars on gui side for donecanvasdialog

- src/g_graph.c
redraw cord lines on visible parent patch for `goprect` message.
closes #2724
> update cords for goprect message

- src/g_scalar.c
fixes #2750
The function `g_scalar.c/word_initvec()` was designed to optimize the creation of datastructure arrays: it only creates a single instance, then copies the memory content of this instance to the other ones.
However, it does not work when the instantiated template contains `array` or `text` fields, because in this case each instance must allocate its own memory.
This PR fixes that, by testing if the template contains other fields type than "flat" floats and symbols, and if so, properly allocating each instance using `g_scalar.c/word_init()`.
> fix ds array init when instantiated template contains arrays or texts

- src/s_audio_jack.c
- src/s_audio_pa.c
`sched_idletask()` may turn off DSP or change audio settings. In this case, we must return early with `SENDDACS_NO`!
Fixes https://github.com/pure-data/pure-data/issues/2760, which is a serious regression in Pd 0.56 caused by 73acd66c8a04a151404ef4a6c2f0edae0214f10d.
> Fix possible crash in sched_send_dacs()
