tcl/pd_deken.tcl

@millerpuckette this is a progressbar improvement to the deken plugin from @umlaeute.

Deken progressbar

---

extra/pd~/GNUmakefile.am

so 'make distcheck' succeeds...

added binarymsg.c to GNUmakefile.am

---

po/Makefile.am
po/es.po

Spanish GUI translation, with recent deken strings.
Hopefully i got it right this time (https://github.com/pure-data/pure-data/pull/126)

added es.po to update/test3-fixes

---

po/pt_br.po

sorry for so many updates, but you know how it is ;)

mores updates to pt_br.po

---

po/af.po
po/az.po
po/be.po
po/bg.po
po/de.po
po/el.po
po/en_ca.po
po/eu.po
po/fr.po
po/gu.po
po/he.po
po/hi.po
po/hu.po
po/it.po
po/pa.po
po/pt_br.po
po/pt_pt.po
po/sq.po
po/sv.po
po/template.pot
po/vi.po
tcl/dialog_find.tcl
tcl/pd_deken.tcl

this pulls in the latest and greatest deken!

Deken update

---

po/fr.po

adding and correcting more French translation in the po file

more french translation

---

po/pt_br.po

this should be the last revision for 0.48 - sorry for so many versions

Update brazilian portuguese translation

---

po/README.txt

A small readme update from pd-list.

added info about setting lang on Windows & creating a bat wrapper

---

po/pt_br.po

they were added in https://github.com/pure-data/pure-data/pull/140

Update pt_br.po (translating newly added strings)

---

tcl/dialog_array.tcl
tcl/dialog_audio.tcl
tcl/dialog_canvas.tcl
tcl/dialog_data.tcl
tcl/dialog_find.tcl
tcl/dialog_font.tcl
tcl/dialog_gatom.tcl
tcl/dialog_iemgui.tcl
tcl/dialog_message.tcl
tcl/dialog_midi.tcl
tcl/helpbrowser.tcl
tcl/pd_deken.tcl
tcl/scrollbox.tcl

This is a PR for bug fixes and updates from the 0.48.0test6 feedback.
So far:
* ...?

0.48.0test6 updates

---

tcl/pd-gui.tcl
tcl/pdtk_canvas.tcl

This is a super simple PR to add the `canvas_fill` option pulled straight from Pd-extended.
Any chance to get this in 0.48??

Added canvas_background option from pd-extended

---

tcl/pd-gui.tcl
tcl/pdtk_canvas.tcl

The couple of commits to add `canvas_background` that were merged into `feature/font-metrics`.

Add dangling commits from feature/font-metrics

---

src/g_array.c
src/m_class.c
src/x_text.c

The correction solves this [issue](https://github.com/pure-data/pure-data/issues/243) and is pretty straightforward but I'm not sure that's the best approach. If @millerpuckette or another Pd master could check it. (and sorry for the noise)

Fix multi instance support for [text define] & [array define]

---

doc/5.reference/declare-help.pd
po/af.po
po/az.po
po/be.po
po/bg.po
po/de.po
po/el.po
po/en_ca.po
po/es.po
po/eu.po
po/fr.po
po/gu.po
po/he.po
po/hi.po
po/hu.po
po/it.po
po/pa.po
po/pt_br.po
po/pt_pt.po
po/sq.po
po/sv.po
po/template.pot
po/vi.po
src/d_soundfile.c
src/g_canvas.c
src/g_editor.c

This is a small development branch, `update/0.49`, for the current 0.49 development. I've already put in some warning fixes and stuff missed in previous merges.
@umlaeute Does it make sense to keeping making PRs like this or should we just have a develop branch?

running commits for 0.49

---

doc/5.reference/makefilename-help.pd

this PR adds all patterns and n-tupple substitution examples to [makefilename]

add all patterns and n-tuple substitution examples to [makefilename]

---

src/d_delay.c

* change error to pd_error
* fix typo
* fix regression (spurious warnings on patch load or paste)
see https://github.com/pure-data/pure-data/issues/433

fix regression in d_delay.c

---

src/g_editor.c

OMG: this updates branch keeps getting merged so fast! but here it is again.

updates for 0.49

---

portaudio/portaudio/src/hostapi/coreaudio/pa_mac_core.c

This is a follow up to the assert & error fix/hack so portaudio won't hang when a device is unplugged. This PR now adds *proper* error handling by using a CoreAudio device listener which receives a notification when a device is no longer alive and can abort the portaudio stream.
This should hopefully be a fix for #470 (and tangentially #443).
A 64bit test build with the fix for macOS is here: 
http://docs.danomatika.com/pdbuilds/Pd-0.49-0test3-unplugfix.zip
1. plug in external sound device
2. start Pd & choose the device\*
3. turn on DSP
4. unplug device
5. Pd should not hang and bring an error message
\* _Please repeat 3 times: device as both input/output, only input, & only output_
Mainly, we *should not* see any error messages until the unplug happens and Pd should not hang when this …

better portaudio device unplug handling for macOS

---

src/g_canvas.c
src/g_editor.c

don't call it, if there's no window but we are visible due to GOP
might close (or not) https://github.com/pure-data/pure-data/issues/578
want review from @danomatika and/or @Spacechild1

[WIP] only call canvas_redraw() if we do have a window

---

doc/5.reference/pdcontrol-help.pd

Updates to master for 0.50 development cycle

Update/0.50 #2

---

src/s_file.c

Quick fix for something I overlooked in testing: the key and value strings need to be copied when writing to the plist dictionary, otherwise the memory can become corrupted.

fix plist write corruption

---

src/m_binbuf.c

I made some improvements with regard to memory handling

Memory handling improvements

---

.travis.yml
src/d_soundfile.c
src/g_editor.c
src/s_audio_pa.c
src/u_pdsend.c

running static code-analysis, a few bugs were discovered, as in:
- post-format specifying more arguments then were specified
- unfreed resources for early-exit due to errors
- undefined behaviour (modulo-by-0)
- NULL-pointer checks
this PR fixes these (the relevant coverity-IDs are given in the commits).

fixes for NULL-pointer access, unfreed resources,... discovered by coverity-scan

---

doc/5.reference/help-intro.pd
src/s_audio.c
src/s_loader.c
src/s_midi.c
src/s_net.c

permanent branch `develop` that only gets curated, small, no-brainer changes that can be easily merged into master at any time.
PS: if anybody can explain how to create PRs that are kept open after merging (or at least: can be opened again after merging), that would be fantastic. (it's a bit boring to re-open this PR after each release ;-))
PPS: supersedes #1129
---
Fixes included (this list should get updated whenever a new fix is included. keep in mind that updating the list might be forgotten though...)
- nicer error messages on Windows, when loading a library fails or a socket throws an error
- correct 1-line-description of `[framp~]`
- fix deletion of multi-byte characters in symbol atoms (Closes: #1101)

stable development branch

---

src/Makefile.am
src/d_soundfile.c
src/d_ugen.c
src/g_canvas.c
src/g_editor.c
src/g_rtext.c
src/g_text.c
src/g_undo.h
src/m_sched.c
src/makefile.gnu
src/makefile.mac
src/makefile.mingw
src/s_audio_alsa.c
src/s_audio_alsamm.c
src/s_audio_mmio.c
src/s_audio_pa.c
src/s_midi.c
src/s_net.h
src/s_path.c
src/s_stuff.h
src/x_text.c
src/x_vexp.c
src/x_vexp.h
src/x_vexp_if.c

Found via `codespell v2.0.dev`

Fix typos in src/ directory

---

doc/1.manual/1.introduction.txt
doc/1.manual/x6-a.htm
doc/1.manual/x6.htm

updates to the html documentation

html updates

---

doc/5.reference/expr-help.pd

Documentation updates

---

src/m_class.c

I explain the fix on https://github.com/libpd/libpd/issues/271.

fix thread-safety of pdinstance_free()

---

doc/5.reference/inlet-outlet-help.pd
src/CHANGELOG.txt
src/d_ugen.c
tcl/pd-gui.tcl

Fix various typos

---

doc/1.manual/x1.htm
doc/1.manual/x5.htm

This PR
1. informs new methods for 'list store' and added features to 'array'.
1. small fixes and typos.

[0.52-test1] html updates.

---

doc/Makefile.am

This PR adds `expr.html` and `favicon.ico` to the autotools build.

Add files to the autotools build

---

doc/1.manual/x4.htm

This PR:
- small fixes to chapter 4.

[0.52-test$] html

---

src/g_text.c

this is one of the tasks in https://github.com/pure-data/pure-data/issues/1476
tested here and it seems to work just fine, but of course I'd expect some revision
I also only allowed meaningful characters in number boxes as before, see my discussion also in https://github.com/pure-data/pure-data/issues/1476#issuecomment-994235584

fix symbol box not outputting floats as symbols & only allow meaningful characters in number boxes

---

src/g_vumeter.c

- commit https://github.com/pure-data/pure-data/pull/1024/commits/70c34f2fc0f02b6d83dde028c085ca20e16148dc redraws scale when setting vu_label_font and closes https://github.com/pure-data/pure-data/issues/1022 
- commit 240853f closes #632

[vu] fixes

---

src/g_text.c

also remove redundant gatom_redraw. closes #1663

unqueue gatoms on free

---

doc/6.externs/makefile

tiny improvement...
cant do any harm.
Cheers
Heck

External examples: Improve Makefile for darwin arm (and make clean)

---

doc/1.manual/index.htm
doc/1.manual/x6-c.htm
doc/1.manual/x6.htm

This PR is intended to be merged into `feature/double-extension`. It adds to https://github.com/pure-data/pure-data/pull/1605

HTML: include BSD installation notes from INSTALL.txt

---

src/g_numbox.c

- Closes: https://github.com/pure-data/pure-data/issues/1747
- Closes: https://github.com/pure-data/pure-data/issues/947

fix [nbx] issues and inconsistencies to gatom boxes

---

src/s_inter_gui.c
src/s_main.c

The first commit (10a2e9d756e0179b1c94c066b8dfa479d5a75a1e) fixes a critical crasher bug (https://github.com/pure-data/pure-data/issues/1751).
The remaining 3 commits are mere improvements.

pdgui_vmess() fixes and improvements

---

portmidi/portmidi/pm_mac/pmmacosxcm.c

I just noticed that https://github.com/pure-data/pure-data/pull/641 missed a couple of things of my original PR.
Most notably, `LIMIT_RATE` is still hardcoded in `pmmacosxcm.c`, so `-DLIMIT_RATE=0` in `portmidi/Makefile.am` has no effect, since. I noticed this because of a compiler warning.
@danomatika Can you have a second look? Can this go into develop? Should we also send this upstream?

portmidi: fix rate limiting (again)

---

po/fr.po

update French translation

---

po/es.po

this is ready for https://github.com/pure-data/pure-data/pull/1772.

update Spanish translation

---

doc/1.manual/x6.htm

This PR is to be merged into `htmldocs` branch

html updates accum1

---

src/g_slider.c

Fix #1831.
Fix the regression about setting slider while dragging it;

fix regression about setting slider while dragging it

---

po/Makefile.am
src/g_editor.c
src/m_pd.h
tcl/pdtk_textwindow.tcl

just for testing the githab actions

Devel test

---

src/d_ugen.c

Ammended version of https://github.com/pure-data/pure-data/tree/delay-signal-reusable

Delay signal reusable

---

src/x_connective.c

`[pack]` does not handle reentrancy all that well: it uses unnecessary heap allocations and it does not really work with gpointers. 
This PR essentially backports the better reentrancy handling of the (newer) `[list]` object family.

improve [pack] reentrancy handling

---

tcl/pd_deken.tcl

- Closes: https://github.com/pure-data/deken/issues/298
- Closes: https://github.com/pure-data/deken/issues/288
- fix sha256 verification of downloaded packages
- fix some typos

Update deken to v0.9.14

---

doc/1.manual/pdmanual.css
doc/1.manual/x4.htm
doc/1.manual/x6-a.htm
doc/1.manual/x6.htm

This PR (targeted to `master` branch) documents the new 'double precision' file extensions in chapter 4 and the build instructions on chapter 6.

HTML: document 'Double precision' file extensions and build instructions.

---

INSTALL.txt
doc/1.manual/x6.htm

document '--enable-debug' configure flag in `INSTALL.txt` and html chapter6

document '--enable-debug' configure flag

---

src/g_text.c

make canvas dirty after adding any type of object

---

src/g_editor.c

correct which canvas Pd proposes to save when requested to quit

---

src/g_editor.c

Fixes #2176
Currently, the `"Discard changes?"` dialog is opened each time you "activate" the object, at mouse-up after clicking on it (like after you move it), and there is this #2176 bug.
With this PR, the dialog only opens when you try to type into the object, i.e when there is a real risk that changes will be lost.
This fixes #2176, and, additionally, reduces the number of dialog occurrences to the necessary ones.

ask whether changes should be discarded when typing into a modified abstraction

---

tcl/pd_deken.tcl

deken-v0.9.14 (as shipped with Pd-0.54-1) fails to verify the SHA256 checksum of downloaded packages on *some* Windows installations (it's not entirely clear yet which versions of Windows are affected).
deken-v0.9.16 fixes this regression with the following changes:
- relax the sha256 check slightly (check whether the SHA256 as reported by the .sha256 file is "contained" in the calculated hash (as opposed to "equals") to work around interface quirks on Windows' `certUtil`)
- Closes: https://github.com/pure-data/deken/issues/299
- additional PowerShell implementation for a fast and API-stable SHA256 hash on Windows
- unify sha256 error handling for download-installation and file-installation
- allow the user a one-time override of a sha256 failure
deken-v0.9.14 also would crash macOS>12 …

Import deken v0.9.18

---

doc/1.manual/x2.htm
doc/1.manual/x3.htm
doc/1.manual/x4.htm

'logical' quotation and brackets

---

doc/5.reference/list-help.pd
src/d_soundfile.h
src/s_print.c
tcl/pd-gui.tcl
tcl/pd_deken.tcl
tcl/pd_docsdir.tcl

this PR simply allows Pd-GUI to load with Tcl/Tk-9.0 (but doesn't change any defaults)
my simple preliminary tests indicate, that everything is working
Closes: https://github.com/pure-data/pure-data/issues/2452

Allow Tcl/Tk 9.0

---

src/d_osc.c

add 'clear' message to [vcf~]

---

src/s_audio_jack.c

previously, Pd would (internally) get a list of JACK-clients, and then try to connect both input and output to the very first available client (prioritizing any client that happens to be called `alsa_pcm`).
This worked nicely in the olden days.
Modern systems (e.g. using PipeWire as a JACK replacement daemon), will use more verbose naming schemes, which might (and actually *will*, at least on my systems) result in one soundcard registering multiple names for both input and output, and the primary input client-name can be different from the primary output client-name:
This PR improves the logic on how JACK clients are selected:
- connect Pd's `[adc~]` to the first JACK client that has audio *source* ports
- connect Pd's `[dac~]` to the first JACK client that has audio *sink* ports (even if …

JACK: autoconnections

---

po/he.po

- Hebrew (100%)
[![Weblate translation status](https://hosted.weblate.org/widget/pure-data/pure-data/multi-auto.svg)](https://hosted.weblate.org/projects/pure-data/pure-data/)

translation updates

---

src/x_vexp_fun.c

- Closes https://github.com/pure-data/pure-data/issues/2471

fix crash in expr

---

mac/tcltk-wish.sh
msw/build-nsi.sh
msw/msw-app.sh
msw/tcltk-dir.sh
src/d_soundfile.c
src/g_io.c
src/m_binbuf.c
src/x_connective.c
tcl/pd_bindings.tcl
tcl/pd_guiprefs.tcl
tcl/pd_menucommands.tcl
tcl/pdtk_canvas.tcl

(just merged, and here it is again)
this is the permanent branch `develop` that only gets curated, small, no-brainer changes that can be easily merged into master at any time.
(as a general rule-of-thumb we shouldn't include changes to `.pd`-files (including help patches!) in this PR, as it is just too easy to end up with unresolvable file conflicts.).
it supersedes https://github.com/pure-data/pure-data/pull/2474
---
- Closes: https://github.com/pure-data/pure-data/issues/2487
- Closes: https://github.com/pure-data/pure-data/issues/2485 
- Closes: https://github.com/pure-data/pure-data/issues/2505
- skip BOM-headers that might occur in a text-file that was edited with some microsoft tool
- print warnings when `[soundfiler]` encounters non-numeric values while reading ASCII files
- …

 stable development branch

---

src/x_connective.c

1st commit is a simple addition to include '%F'.
I wasn't planing on making a 2nd commit, but here it is and it: 
- closes https://github.com/pure-data/pure-data/issues/2508
If it is too intrusive for the 'development' branch let me know
Of course I will add these to the docs after it all gets merged

improvements to [makefilename]

---

src/d_math.c

This PR implements perform8 methods for the following objects:
- `[wrap~]`
- `[clip~]`
- `[abs~]`
- `[sqrt~]`
- `[rsqrt~]`
I did a side to side comparison (with the same compiler settings) and with GCC and Clang I get consistent 2-3x speedups on x86_64.
For anyone interested, here is the assembly output for each routine:
<details>
<summary>Click me</summary>
https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQAJlIOAMngMmABy7gBGmMQgkgDspAAOqAqEtgzObh7eCUkpAgFBoSwRUbEWmFY2AkIETMQE6e6ePpaY1qnVtQT5IeGR0XEKNXUNmc1DXYE9RX2xAJQWqK7EyOwcAKReAMyByG5YANRrm46D%2BIIAdAhH2GsaAIIb2wy7rgdHjrR4LIQKl9e3D3uBAAnvFMFgqPtAgR4gRiMYCPsCMZoUcAEIAkFgiH7Ki0VBMRHIhSseL0dEAylbCGTfYAdQASndlMZHH4AJLKaizfZQbmHTbYXnE0n …

Implement missing perform8 methods in d_math.c

---

src/d_soundfile.c

`[readsf~]` now takes an optional `-m` flag before the `channels` argument which creates a multichannel signal outlet instead of individual signal outlets. The number of channels can also be set dynamically with the `[channels(` message, similar to other multichannel objects.
---
`[writesf~]` simply accepts multichannel input signals, similar to `[dac~]`, and the `[open(` takes the current number of channels. If the input channel count changes while the object is streaming, it will print a warning to the console.
There is one caveat: if the input signal is multichannel, you must send the `[open(` message *after* DSP is turned on, otherwise it would create a singlechannel file and you get a warning (as described above).
---
Closes #1990

multichannel support for readsf~ and writesf~

---

src/g_graph.c

compilation is broken in current master ( see https://github.com/pure-data/pure-data/commit/67abdeebdad1b944b834d6a66dd9cbce91dace45 ) - edited by porres

Add missing parenthesis and fix compilation error in current master
